[package]
name = "fdir-storage"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
fdir-canonical = { path = "../fdir-canonical" }
fdir-core = { path = "../fdir-core" }

[lints]
workspace = true
