// @generated by tools/generate_rust_contract.py; do not edit.
// The language-neutral machine model and canonical vector remain authoritative.

/// Identifier of the frozen language-neutral logical model.
pub const MODEL_ID: &str = "https://fdir.dev/model/2.1";
/// Version of the frozen language-neutral logical model.
pub const MODEL_VERSION: &str = "2.1.0";
/// Root entity declared by the logical model.
pub const ROOT_ENTITY: &str = "Snapshot";
/// SHA-256 of the canonical-vector source bytes.
pub const CANONICAL_VECTOR_SHA256: &str = "7d1897743f643096a37625e50ac6deeb8cda8443ec63890f1f1ba17726f33dc5";
/// Byte length of the canonical-vector source.
pub const CANONICAL_VECTOR_LENGTH: usize = 342;
/// Canonical vector compiled directly from the repository authority.
pub const CANONICAL_VECTOR_JSON: &str = include_str!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../../fixtures/canonical/vector.json"
));

/// Entity names in authority order.
pub const ENTITY_NAMES: &[&str] = &[
    "Artifact",
    "Carrier",
    "Surface",
    "Geometry",
    "Selector",
    "Occurrence",
    "Observation",
    "InventoryDomain",
    "AccountingItem",
    "IndependentCensusReceipt",
    "InformationUnit",
    "RecordAssertion",
    "InformationRelation",
    "AcceptedProjection",
    "InterpretationContext",
    "GuaranteeStatus",
    "EquivalenceCertificate",
    "LineageCertificate",
    "Diagnostic",
    "Snapshot",
];

/// Enumeration names in deterministic lexical order.
pub const ENUM_NAMES: &[&str] = &[
    "AccountingDisposition",
    "AssertionStatus",
    "CompletenessState",
    "DiagnosticSeverity",
    "EquivalenceOutcome",
    "RelationKind",
    "UnitKind",
    "Visibility",
];
