// @generated by tools/generate_rust_contract.py; do not edit.
// The language-neutral machine model and canonical vector remain authoritative.

#[rustfmt::skip]
mod generated_contract {
    use std::fmt::{self, Display, Formatter};
    use std::str::FromStr;

    /// Identifier of the frozen language-neutral logical model.
    pub const MODEL_ID: &str = "https://fdir.dev/model/2.1";
    /// Version of the frozen language-neutral logical model.
    pub const MODEL_VERSION: &str = "2.1.0";
    /// Root entity declared by the logical model.
    pub const ROOT_ENTITY: &str = "Snapshot";
    /// SHA-256 of the canonical-vector source bytes.
    pub const CANONICAL_VECTOR_SHA256: &str = "1b455af0224e20dc9eb0737b84e13f50a389553ad0e0b54b21fafa1154b3070d";
    /// Byte length of the canonical-vector source.
    pub const CANONICAL_VECTOR_LENGTH: usize = 7597;
    /// Canonical vector compiled directly from the repository authority.
    pub const CANONICAL_VECTOR_JSON: &str = include_str!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../fixtures/canonical/vector.json"
    ));

    /// Entity names in authority order.
    pub const ENTITY_NAMES: &[&str] = &[
        "Artifact",
        "Carrier",
        "Surface",
        "Geometry",
        "Selector",
        "Occurrence",
        "Observation",
        "InventoryDomain",
        "AccountingItem",
        "IndependentCensusReceipt",
        "InformationUnit",
        "RecordAssertion",
        "InformationRelation",
        "AcceptedProjection",
        "InterpretationContext",
        "GuaranteeStatus",
        "EquivalenceCertificate",
        "LineageCertificate",
        "Diagnostic",
        "Snapshot",
    ];

    /// Enumeration names in deterministic lexical order.
    pub const ENUM_NAMES: &[&str] = &[
        "AccountingDisposition",
        "AssertionStatus",
        "CompletenessState",
        "DiagnosticSeverity",
        "EquivalenceOutcome",
        "RelationKind",
        "UnitKind",
        "Visibility",
    ];

    macro_rules! define_strong_id {
        ($name:ident) => {
            #[derive(Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
            pub struct $name(crate::Identifier);

            impl $name {
                /// Construct a non-empty, entity-specific identifier.
                pub fn new(value: impl Into<String>) -> Result<Self, crate::ValueError> {
                    crate::Identifier::new(value).map(Self)
                }

                /// Borrow the exact identifier text.
                pub fn as_str(&self) -> &str {
                    self.0.as_str()
                }

                /// Consume the identifier and return its text.
                pub fn into_string(self) -> String {
                    self.0.into_string()
                }
            }

            impl AsRef<str> for $name {
                fn as_ref(&self) -> &str {
                    self.as_str()
                }
            }

            impl Display for $name {
                fn fmt(&self, formatter: &mut Formatter<'_>) -> fmt::Result {
                    formatter.write_str(self.as_str())
                }
            }

            impl FromStr for $name {
                type Err = crate::ValueError;

                fn from_str(value: &str) -> Result<Self, Self::Err> {
                    Self::new(value)
                }
            }
        };
    }

    define_strong_id!(AccountingItemId);
    define_strong_id!(ArtifactId);
    define_strong_id!(AssertionId);
    define_strong_id!(CarrierId);
    define_strong_id!(CertificateId);
    define_strong_id!(ContextId);
    define_strong_id!(DiagnosticId);
    define_strong_id!(GeometryId);
    define_strong_id!(GuaranteeStatusId);
    define_strong_id!(InventoryDomainId);
    define_strong_id!(LineageCertificateId);
    define_strong_id!(ObservationId);
    define_strong_id!(OccurrenceId);
    define_strong_id!(OpaqueId);
    define_strong_id!(ProjectionId);
    define_strong_id!(ReceiptId);
    define_strong_id!(RelationId);
    define_strong_id!(SelectorId);
    define_strong_id!(SnapshotId);
    define_strong_id!(SurfaceId);
    define_strong_id!(UnitId);

    #[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
    pub enum AccountingDisposition {
        Represented,
        Residual,
        Unsupported,
        Unreadable,
        PolicyExcluded,
        Duplicate,
    }

    impl AccountingDisposition {
        pub const ALL: [Self; 6] = [
            Self::Represented,
            Self::Residual,
            Self::Unsupported,
            Self::Unreadable,
            Self::PolicyExcluded,
            Self::Duplicate,
        ];

        /// Stable machine-readable value from the logical model.
        pub const fn as_str(self) -> &'static str {
            match self {
                Self::Represented => "represented",
                Self::Residual => "residual",
                Self::Unsupported => "unsupported",
                Self::Unreadable => "unreadable",
                Self::PolicyExcluded => "policy-excluded",
                Self::Duplicate => "duplicate",
            }
        }

        /// Parse a value without accepting an unknown variant as success.
        pub fn parse(value: &str) -> Result<Self, crate::UnknownEnumValue> {
            match value {
                "represented" => Ok(Self::Represented),
                "residual" => Ok(Self::Residual),
                "unsupported" => Ok(Self::Unsupported),
                "unreadable" => Ok(Self::Unreadable),
                "policy-excluded" => Ok(Self::PolicyExcluded),
                "duplicate" => Ok(Self::Duplicate),
                _ => Err(crate::UnknownEnumValue::new("AccountingDisposition", value)),
            }
        }
    }

    impl Display for AccountingDisposition {
        fn fmt(&self, formatter: &mut Formatter<'_>) -> fmt::Result {
            formatter.write_str(self.as_str())
        }
    }

    impl TryFrom<&str> for AccountingDisposition {
        type Error = crate::UnknownEnumValue;

        fn try_from(value: &str) -> Result<Self, crate::UnknownEnumValue> {
            Self::parse(value)
        }
    }

    #[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
    pub enum AssertionStatus {
        Accepted,
        Candidate,
        Rejected,
        Superseded,
        Unresolved,
    }

    impl AssertionStatus {
        pub const ALL: [Self; 5] = [
            Self::Accepted,
            Self::Candidate,
            Self::Rejected,
            Self::Superseded,
            Self::Unresolved,
        ];

        /// Stable machine-readable value from the logical model.
        pub const fn as_str(self) -> &'static str {
            match self {
                Self::Accepted => "accepted",
                Self::Candidate => "candidate",
                Self::Rejected => "rejected",
                Self::Superseded => "superseded",
                Self::Unresolved => "unresolved",
            }
        }

        /// Parse a value without accepting an unknown variant as success.
        pub fn parse(value: &str) -> Result<Self, crate::UnknownEnumValue> {
            match value {
                "accepted" => Ok(Self::Accepted),
                "candidate" => Ok(Self::Candidate),
                "rejected" => Ok(Self::Rejected),
                "superseded" => Ok(Self::Superseded),
                "unresolved" => Ok(Self::Unresolved),
                _ => Err(crate::UnknownEnumValue::new("AssertionStatus", value)),
            }
        }
    }

    impl Display for AssertionStatus {
        fn fmt(&self, formatter: &mut Formatter<'_>) -> fmt::Result {
            formatter.write_str(self.as_str())
        }
    }

    impl TryFrom<&str> for AssertionStatus {
        type Error = crate::UnknownEnumValue;

        fn try_from(value: &str) -> Result<Self, crate::UnknownEnumValue> {
            Self::parse(value)
        }
    }

    #[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
    pub enum CompletenessState {
        Complete,
        Partial,
        Unsupported,
        Unresolved,
        Cancelled,
        Failed,
    }

    impl CompletenessState {
        pub const ALL: [Self; 6] = [
            Self::Complete,
            Self::Partial,
            Self::Unsupported,
            Self::Unresolved,
            Self::Cancelled,
            Self::Failed,
        ];

        /// Stable machine-readable value from the logical model.
        pub const fn as_str(self) -> &'static str {
            match self {
                Self::Complete => "complete",
                Self::Partial => "partial",
                Self::Unsupported => "unsupported",
                Self::Unresolved => "unresolved",
                Self::Cancelled => "cancelled",
                Self::Failed => "failed",
            }
        }

        /// Parse a value without accepting an unknown variant as success.
        pub fn parse(value: &str) -> Result<Self, crate::UnknownEnumValue> {
            match value {
                "complete" => Ok(Self::Complete),
                "partial" => Ok(Self::Partial),
                "unsupported" => Ok(Self::Unsupported),
                "unresolved" => Ok(Self::Unresolved),
                "cancelled" => Ok(Self::Cancelled),
                "failed" => Ok(Self::Failed),
                _ => Err(crate::UnknownEnumValue::new("CompletenessState", value)),
            }
        }
    }

    impl Display for CompletenessState {
        fn fmt(&self, formatter: &mut Formatter<'_>) -> fmt::Result {
            formatter.write_str(self.as_str())
        }
    }

    impl TryFrom<&str> for CompletenessState {
        type Error = crate::UnknownEnumValue;

        fn try_from(value: &str) -> Result<Self, crate::UnknownEnumValue> {
            Self::parse(value)
        }
    }

    #[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
    pub enum DiagnosticSeverity {
        Info,
        Warning,
        Error,
        Fatal,
    }

    impl DiagnosticSeverity {
        pub const ALL: [Self; 4] = [
            Self::Info,
            Self::Warning,
            Self::Error,
            Self::Fatal,
        ];

        /// Stable machine-readable value from the logical model.
        pub const fn as_str(self) -> &'static str {
            match self {
                Self::Info => "info",
                Self::Warning => "warning",
                Self::Error => "error",
                Self::Fatal => "fatal",
            }
        }

        /// Parse a value without accepting an unknown variant as success.
        pub fn parse(value: &str) -> Result<Self, crate::UnknownEnumValue> {
            match value {
                "info" => Ok(Self::Info),
                "warning" => Ok(Self::Warning),
                "error" => Ok(Self::Error),
                "fatal" => Ok(Self::Fatal),
                _ => Err(crate::UnknownEnumValue::new("DiagnosticSeverity", value)),
            }
        }
    }

    impl Display for DiagnosticSeverity {
        fn fmt(&self, formatter: &mut Formatter<'_>) -> fmt::Result {
            formatter.write_str(self.as_str())
        }
    }

    impl TryFrom<&str> for DiagnosticSeverity {
        type Error = crate::UnknownEnumValue;

        fn try_from(value: &str) -> Result<Self, crate::UnknownEnumValue> {
            Self::parse(value)
        }
    }

    #[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
    pub enum EquivalenceOutcome {
        Equivalent,
        NotEquivalent,
        Indeterminate,
    }

    impl EquivalenceOutcome {
        pub const ALL: [Self; 3] = [
            Self::Equivalent,
            Self::NotEquivalent,
            Self::Indeterminate,
        ];

        /// Stable machine-readable value from the logical model.
        pub const fn as_str(self) -> &'static str {
            match self {
                Self::Equivalent => "equivalent",
                Self::NotEquivalent => "not-equivalent",
                Self::Indeterminate => "indeterminate",
            }
        }

        /// Parse a value without accepting an unknown variant as success.
        pub fn parse(value: &str) -> Result<Self, crate::UnknownEnumValue> {
            match value {
                "equivalent" => Ok(Self::Equivalent),
                "not-equivalent" => Ok(Self::NotEquivalent),
                "indeterminate" => Ok(Self::Indeterminate),
                _ => Err(crate::UnknownEnumValue::new("EquivalenceOutcome", value)),
            }
        }
    }

    impl Display for EquivalenceOutcome {
        fn fmt(&self, formatter: &mut Formatter<'_>) -> fmt::Result {
            formatter.write_str(self.as_str())
        }
    }

    impl TryFrom<&str> for EquivalenceOutcome {
        type Error = crate::UnknownEnumValue;

        fn try_from(value: &str) -> Result<Self, crate::UnknownEnumValue> {
            Self::parse(value)
        }
    }

    #[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
    pub enum RelationKind {
        Contains,
        Precedes,
        References,
        Annotates,
        Groups,
        DerivedFrom,
        Continues,
    }

    impl RelationKind {
        pub const ALL: [Self; 7] = [
            Self::Contains,
            Self::Precedes,
            Self::References,
            Self::Annotates,
            Self::Groups,
            Self::DerivedFrom,
            Self::Continues,
        ];

        /// Stable machine-readable value from the logical model.
        pub const fn as_str(self) -> &'static str {
            match self {
                Self::Contains => "contains",
                Self::Precedes => "precedes",
                Self::References => "references",
                Self::Annotates => "annotates",
                Self::Groups => "groups",
                Self::DerivedFrom => "derived-from",
                Self::Continues => "continues",
            }
        }

        /// Parse a value without accepting an unknown variant as success.
        pub fn parse(value: &str) -> Result<Self, crate::UnknownEnumValue> {
            match value {
                "contains" => Ok(Self::Contains),
                "precedes" => Ok(Self::Precedes),
                "references" => Ok(Self::References),
                "annotates" => Ok(Self::Annotates),
                "groups" => Ok(Self::Groups),
                "derived-from" => Ok(Self::DerivedFrom),
                "continues" => Ok(Self::Continues),
                _ => Err(crate::UnknownEnumValue::new("RelationKind", value)),
            }
        }
    }

    impl Display for RelationKind {
        fn fmt(&self, formatter: &mut Formatter<'_>) -> fmt::Result {
            formatter.write_str(self.as_str())
        }
    }

    impl TryFrom<&str> for RelationKind {
        type Error = crate::UnknownEnumValue;

        fn try_from(value: &str) -> Result<Self, crate::UnknownEnumValue> {
            Self::parse(value)
        }
    }

    #[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
    pub enum UnitKind {
        Document,
        Section,
        Paragraph,
        Span,
        List,
        ListItem,
        Table,
        Row,
        Cell,
        Figure,
        Formula,
        Field,
        Note,
        Comment,
        Custom,
    }

    impl UnitKind {
        pub const ALL: [Self; 15] = [
            Self::Document,
            Self::Section,
            Self::Paragraph,
            Self::Span,
            Self::List,
            Self::ListItem,
            Self::Table,
            Self::Row,
            Self::Cell,
            Self::Figure,
            Self::Formula,
            Self::Field,
            Self::Note,
            Self::Comment,
            Self::Custom,
        ];

        /// Stable machine-readable value from the logical model.
        pub const fn as_str(self) -> &'static str {
            match self {
                Self::Document => "document",
                Self::Section => "section",
                Self::Paragraph => "paragraph",
                Self::Span => "span",
                Self::List => "list",
                Self::ListItem => "list-item",
                Self::Table => "table",
                Self::Row => "row",
                Self::Cell => "cell",
                Self::Figure => "figure",
                Self::Formula => "formula",
                Self::Field => "field",
                Self::Note => "note",
                Self::Comment => "comment",
                Self::Custom => "custom",
            }
        }

        /// Parse a value without accepting an unknown variant as success.
        pub fn parse(value: &str) -> Result<Self, crate::UnknownEnumValue> {
            match value {
                "document" => Ok(Self::Document),
                "section" => Ok(Self::Section),
                "paragraph" => Ok(Self::Paragraph),
                "span" => Ok(Self::Span),
                "list" => Ok(Self::List),
                "list-item" => Ok(Self::ListItem),
                "table" => Ok(Self::Table),
                "row" => Ok(Self::Row),
                "cell" => Ok(Self::Cell),
                "figure" => Ok(Self::Figure),
                "formula" => Ok(Self::Formula),
                "field" => Ok(Self::Field),
                "note" => Ok(Self::Note),
                "comment" => Ok(Self::Comment),
                "custom" => Ok(Self::Custom),
                _ => Err(crate::UnknownEnumValue::new("UnitKind", value)),
            }
        }
    }

    impl Display for UnitKind {
        fn fmt(&self, formatter: &mut Formatter<'_>) -> fmt::Result {
            formatter.write_str(self.as_str())
        }
    }

    impl TryFrom<&str> for UnitKind {
        type Error = crate::UnknownEnumValue;

        fn try_from(value: &str) -> Result<Self, crate::UnknownEnumValue> {
            Self::parse(value)
        }
    }

    #[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
    pub enum Visibility {
        Visible,
        Hidden,
        Conditional,
        Unknown,
    }

    impl Visibility {
        pub const ALL: [Self; 4] = [
            Self::Visible,
            Self::Hidden,
            Self::Conditional,
            Self::Unknown,
        ];

        /// Stable machine-readable value from the logical model.
        pub const fn as_str(self) -> &'static str {
            match self {
                Self::Visible => "visible",
                Self::Hidden => "hidden",
                Self::Conditional => "conditional",
                Self::Unknown => "unknown",
            }
        }

        /// Parse a value without accepting an unknown variant as success.
        pub fn parse(value: &str) -> Result<Self, crate::UnknownEnumValue> {
            match value {
                "visible" => Ok(Self::Visible),
                "hidden" => Ok(Self::Hidden),
                "conditional" => Ok(Self::Conditional),
                "unknown" => Ok(Self::Unknown),
                _ => Err(crate::UnknownEnumValue::new("Visibility", value)),
            }
        }
    }

    impl Display for Visibility {
        fn fmt(&self, formatter: &mut Formatter<'_>) -> fmt::Result {
            formatter.write_str(self.as_str())
        }
    }

    impl TryFrom<&str> for Visibility {
        type Error = crate::UnknownEnumValue;

        fn try_from(value: &str) -> Result<Self, crate::UnknownEnumValue> {
            Self::parse(value)
        }
    }

    #[derive(Clone, Debug, PartialEq)]
    pub struct Artifact {
        /// JSON property `artifactId`.
        pub artifact_id: ArtifactId,
        /// JSON property `byteLength`.
        pub byte_length: Option<u64>,
        /// JSON property `digest`.
        pub digest: crate::Digest,
        /// JSON property `mediaType`.
        pub media_type: String,
        /// JSON property `role`.
        pub role: Option<String>,
        /// Unknown extension members retained without granting them core authority.
        pub extensions: crate::ExtensionMap,
    }

    impl Artifact {
        /// Construct the entity with every machine-required property present.
        #[allow(clippy::too_many_arguments)]
        pub fn new(
            artifact_id: ArtifactId,
            media_type: String,
            digest: crate::Digest,
        ) -> Self {
            Self {
                artifact_id,
                byte_length: None,
                digest,
                media_type,
                role: None,
                extensions: crate::ExtensionMap::new(),
            }
        }
    }

    #[derive(Clone, Debug, PartialEq)]
    pub struct Carrier {
        /// JSON property `artifactId`.
        pub artifact_id: ArtifactId,
        /// JSON property `carrierId`.
        pub carrier_id: CarrierId,
        /// JSON property `carrierType`.
        pub carrier_type: String,
        /// JSON property `path`.
        pub path: Option<String>,
        /// Unknown extension members retained without granting them core authority.
        pub extensions: crate::ExtensionMap,
    }

    impl Carrier {
        /// Construct the entity with every machine-required property present.
        #[allow(clippy::too_many_arguments)]
        pub fn new(
            carrier_id: CarrierId,
            artifact_id: ArtifactId,
            carrier_type: String,
        ) -> Self {
            Self {
                artifact_id,
                carrier_id,
                carrier_type,
                path: None,
                extensions: crate::ExtensionMap::new(),
            }
        }
    }

    #[derive(Clone, Debug, PartialEq)]
    pub struct Surface {
        /// JSON property `carrierId`.
        pub carrier_id: CarrierId,
        /// JSON property `label`.
        pub label: Option<String>,
        /// JSON property `surfaceId`.
        pub surface_id: SurfaceId,
        /// JSON property `surfaceType`.
        pub surface_type: String,
        /// Unknown extension members retained without granting them core authority.
        pub extensions: crate::ExtensionMap,
    }

    impl Surface {
        /// Construct the entity with every machine-required property present.
        #[allow(clippy::too_many_arguments)]
        pub fn new(
            surface_id: SurfaceId,
            carrier_id: CarrierId,
            surface_type: String,
        ) -> Self {
            Self {
                carrier_id,
                label: None,
                surface_id,
                surface_type,
                extensions: crate::ExtensionMap::new(),
            }
        }
    }

    #[derive(Clone, Debug, PartialEq)]
    pub struct Geometry {
        /// JSON property `bounds`.
        pub bounds: Vec<crate::FiniteNumber>,
        /// JSON property `coordinateSpace`.
        pub coordinate_space: String,
        /// JSON property `geometryId`.
        pub geometry_id: GeometryId,
        /// JSON property `surfaceId`.
        pub surface_id: SurfaceId,
        /// Unknown extension members retained without granting them core authority.
        pub extensions: crate::ExtensionMap,
    }

    impl Geometry {
        /// Construct the entity with every machine-required property present.
        #[allow(clippy::too_many_arguments)]
        pub fn new(
            geometry_id: GeometryId,
            surface_id: SurfaceId,
            coordinate_space: String,
            bounds: Vec<crate::FiniteNumber>,
        ) -> Self {
            Self {
                bounds,
                coordinate_space,
                geometry_id,
                surface_id,
                extensions: crate::ExtensionMap::new(),
            }
        }
    }

    #[derive(Clone, Debug, PartialEq)]
    pub struct Selector {
        /// JSON property `selectorId`.
        pub selector_id: SelectorId,
        /// JSON property `selectorType`.
        pub selector_type: String,
        /// JSON property `value`.
        pub value: crate::ObjectValue,
        /// Unknown extension members retained without granting them core authority.
        pub extensions: crate::ExtensionMap,
    }

    impl Selector {
        /// Construct the entity with every machine-required property present.
        #[allow(clippy::too_many_arguments)]
        pub fn new(
            selector_id: SelectorId,
            selector_type: String,
            value: crate::ObjectValue,
        ) -> Self {
            Self {
                selector_id,
                selector_type,
                value,
                extensions: crate::ExtensionMap::new(),
            }
        }
    }

    #[derive(Clone, Debug, PartialEq)]
    pub struct Occurrence {
        /// JSON property `carrierId`.
        pub carrier_id: CarrierId,
        /// JSON property `geometryIds`.
        pub geometry_ids: Option<Vec<GeometryId>>,
        /// JSON property `occurrenceId`.
        pub occurrence_id: OccurrenceId,
        /// JSON property `selectorIds`.
        pub selector_ids: Vec<SelectorId>,
        /// Unknown extension members retained without granting them core authority.
        pub extensions: crate::ExtensionMap,
    }

    impl Occurrence {
        /// Construct the entity with every machine-required property present.
        #[allow(clippy::too_many_arguments)]
        pub fn new(
            occurrence_id: OccurrenceId,
            carrier_id: CarrierId,
            selector_ids: Vec<SelectorId>,
        ) -> Self {
            Self {
                carrier_id,
                geometry_ids: None,
                occurrence_id,
                selector_ids,
                extensions: crate::ExtensionMap::new(),
            }
        }
    }

    #[derive(Clone, Debug, PartialEq)]
    pub struct Observation {
        /// JSON property `confidence`.
        pub confidence: Option<crate::FiniteNumber>,
        /// JSON property `method`.
        pub method: String,
        /// JSON property `observationId`.
        pub observation_id: ObservationId,
        /// JSON property `occurrenceId`.
        pub occurrence_id: OccurrenceId,
        /// JSON property `value`.
        pub value: crate::CanonicalValue,
        /// Unknown extension members retained without granting them core authority.
        pub extensions: crate::ExtensionMap,
    }

    impl Observation {
        /// Construct the entity with every machine-required property present.
        #[allow(clippy::too_many_arguments)]
        pub fn new(
            observation_id: ObservationId,
            occurrence_id: OccurrenceId,
            method: String,
            value: crate::CanonicalValue,
        ) -> Self {
            Self {
                confidence: None,
                method,
                observation_id,
                occurrence_id,
                value,
                extensions: crate::ExtensionMap::new(),
            }
        }
    }

    #[derive(Clone, Debug, PartialEq)]
    pub struct InventoryDomain {
        /// JSON property `carrierId`.
        pub carrier_id: CarrierId,
        /// JSON property `domainType`.
        pub domain_type: String,
        /// JSON property `expectedCount`.
        pub expected_count: Option<u64>,
        /// JSON property `inventoryDomainId`.
        pub inventory_domain_id: InventoryDomainId,
        /// Unknown extension members retained without granting them core authority.
        pub extensions: crate::ExtensionMap,
    }

    impl InventoryDomain {
        /// Construct the entity with every machine-required property present.
        #[allow(clippy::too_many_arguments)]
        pub fn new(
            inventory_domain_id: InventoryDomainId,
            carrier_id: CarrierId,
            domain_type: String,
        ) -> Self {
            Self {
                carrier_id,
                domain_type,
                expected_count: None,
                inventory_domain_id,
                extensions: crate::ExtensionMap::new(),
            }
        }
    }

    #[derive(Clone, Debug, PartialEq)]
    pub struct AccountingItem {
        /// JSON property `accountingItemId`.
        pub accounting_item_id: AccountingItemId,
        /// JSON property `diagnosticIds`.
        pub diagnostic_ids: Option<Vec<DiagnosticId>>,
        /// JSON property `disposition`.
        pub disposition: AccountingDisposition,
        /// JSON property `inventoryDomainId`.
        pub inventory_domain_id: InventoryDomainId,
        /// JSON property `sourceKey`.
        pub source_key: String,
        /// JSON property `unitIds`.
        pub unit_ids: Option<Vec<UnitId>>,
        /// Unknown extension members retained without granting them core authority.
        pub extensions: crate::ExtensionMap,
    }

    impl AccountingItem {
        /// Construct the entity with every machine-required property present.
        #[allow(clippy::too_many_arguments)]
        pub fn new(
            accounting_item_id: AccountingItemId,
            inventory_domain_id: InventoryDomainId,
            source_key: String,
            disposition: AccountingDisposition,
        ) -> Self {
            Self {
                accounting_item_id,
                diagnostic_ids: None,
                disposition,
                inventory_domain_id,
                source_key,
                unit_ids: None,
                extensions: crate::ExtensionMap::new(),
            }
        }
    }

    #[derive(Clone, Debug, PartialEq)]
    pub struct IndependentCensusReceipt {
        /// JSON property `digest`.
        pub digest: crate::Digest,
        /// JSON property `inventoryDomainId`.
        pub inventory_domain_id: InventoryDomainId,
        /// JSON property `observedCount`.
        pub observed_count: u64,
        /// JSON property `receiptId`.
        pub receipt_id: ReceiptId,
        /// Unknown extension members retained without granting them core authority.
        pub extensions: crate::ExtensionMap,
    }

    impl IndependentCensusReceipt {
        /// Construct the entity with every machine-required property present.
        #[allow(clippy::too_many_arguments)]
        pub fn new(
            receipt_id: ReceiptId,
            inventory_domain_id: InventoryDomainId,
            observed_count: u64,
            digest: crate::Digest,
        ) -> Self {
            Self {
                digest,
                inventory_domain_id,
                observed_count,
                receipt_id,
                extensions: crate::ExtensionMap::new(),
            }
        }
    }

    #[derive(Clone, Debug, PartialEq)]
    pub struct InformationUnit {
        /// JSON property `unitId`.
        pub unit_id: UnitId,
        /// Unknown extension members retained without granting them core authority.
        pub extensions: crate::ExtensionMap,
    }

    impl InformationUnit {
        /// Construct the entity with every machine-required property present.
        #[allow(clippy::too_many_arguments)]
        pub fn new(
            unit_id: UnitId,
        ) -> Self {
            Self {
                unit_id,
                extensions: crate::ExtensionMap::new(),
            }
        }
    }

    #[derive(Clone, Debug, PartialEq)]
    pub struct RecordAssertion {
        /// JSON property `assertionId`.
        pub assertion_id: AssertionId,
        /// JSON property `confidence`.
        pub confidence: Option<crate::FiniteNumber>,
        /// JSON property `contextId`.
        pub context_id: Option<ContextId>,
        /// JSON property `occurrenceIds`.
        pub occurrence_ids: Vec<OccurrenceId>,
        /// JSON property `predicate`.
        pub predicate: String,
        /// JSON property `status`.
        pub status: AssertionStatus,
        /// JSON property `unitId`.
        pub unit_id: UnitId,
        /// JSON property `value`.
        pub value: crate::CanonicalValue,
        /// Unknown extension members retained without granting them core authority.
        pub extensions: crate::ExtensionMap,
    }

    impl RecordAssertion {
        /// Construct the entity with every machine-required property present.
        #[allow(clippy::too_many_arguments)]
        pub fn new(
            assertion_id: AssertionId,
            unit_id: UnitId,
            predicate: String,
            value: crate::CanonicalValue,
            status: AssertionStatus,
            occurrence_ids: Vec<OccurrenceId>,
        ) -> Self {
            Self {
                assertion_id,
                confidence: None,
                context_id: None,
                occurrence_ids,
                predicate,
                status,
                unit_id,
                value,
                extensions: crate::ExtensionMap::new(),
            }
        }
    }

    #[derive(Clone, Debug, PartialEq)]
    pub struct InformationRelation {
        /// JSON property `occurrenceIds`.
        pub occurrence_ids: Option<Vec<OccurrenceId>>,
        /// JSON property `relationId`.
        pub relation_id: RelationId,
        /// JSON property `relationKind`.
        pub relation_kind: RelationKind,
        /// JSON property `sourceUnitId`.
        pub source_unit_id: UnitId,
        /// JSON property `status`.
        pub status: AssertionStatus,
        /// JSON property `targetUnitId`.
        pub target_unit_id: UnitId,
        /// Unknown extension members retained without granting them core authority.
        pub extensions: crate::ExtensionMap,
    }

    impl InformationRelation {
        /// Construct the entity with every machine-required property present.
        #[allow(clippy::too_many_arguments)]
        pub fn new(
            relation_id: RelationId,
            source_unit_id: UnitId,
            target_unit_id: UnitId,
            relation_kind: RelationKind,
            status: AssertionStatus,
        ) -> Self {
            Self {
                occurrence_ids: None,
                relation_id,
                relation_kind,
                source_unit_id,
                status,
                target_unit_id,
                extensions: crate::ExtensionMap::new(),
            }
        }
    }

    #[derive(Clone, Debug, PartialEq)]
    pub struct AcceptedProjection {
        /// JSON property `assertionIds`.
        pub assertion_ids: Vec<AssertionId>,
        /// JSON property `projectionId`.
        pub projection_id: ProjectionId,
        /// JSON property `unitId`.
        pub unit_id: UnitId,
        /// JSON property `value`.
        pub value: Option<crate::ObjectValue>,
        /// Unknown extension members retained without granting them core authority.
        pub extensions: crate::ExtensionMap,
    }

    impl AcceptedProjection {
        /// Construct the entity with every machine-required property present.
        #[allow(clippy::too_many_arguments)]
        pub fn new(
            projection_id: ProjectionId,
            unit_id: UnitId,
            assertion_ids: Vec<AssertionId>,
        ) -> Self {
            Self {
                assertion_ids,
                projection_id,
                unit_id,
                value: None,
                extensions: crate::ExtensionMap::new(),
            }
        }
    }

    #[derive(Clone, Debug, PartialEq)]
    pub struct InterpretationContext {
        /// JSON property `contextId`.
        pub context_id: ContextId,
        /// JSON property `parameters`.
        pub parameters: crate::ObjectValue,
        /// Unknown extension members retained without granting them core authority.
        pub extensions: crate::ExtensionMap,
    }

    impl InterpretationContext {
        /// Construct the entity with every machine-required property present.
        #[allow(clippy::too_many_arguments)]
        pub fn new(
            context_id: ContextId,
            parameters: crate::ObjectValue,
        ) -> Self {
            Self {
                context_id,
                parameters,
                extensions: crate::ExtensionMap::new(),
            }
        }
    }

    #[derive(Clone, Debug, PartialEq)]
    pub struct GuaranteeStatus {
        /// JSON property `diagnosticIds`.
        pub diagnostic_ids: Option<Vec<DiagnosticId>>,
        /// JSON property `guaranteeStatusId`.
        pub guarantee_status_id: GuaranteeStatusId,
        /// JSON property `profileId`.
        pub profile_id: String,
        /// JSON property `state`.
        pub state: CompletenessState,
        /// Unknown extension members retained without granting them core authority.
        pub extensions: crate::ExtensionMap,
    }

    impl GuaranteeStatus {
        /// Construct the entity with every machine-required property present.
        #[allow(clippy::too_many_arguments)]
        pub fn new(
            guarantee_status_id: GuaranteeStatusId,
            profile_id: String,
            state: CompletenessState,
        ) -> Self {
            Self {
                diagnostic_ids: None,
                guarantee_status_id,
                profile_id,
                state,
                extensions: crate::ExtensionMap::new(),
            }
        }
    }

    #[derive(Clone, Debug, PartialEq)]
    pub struct EquivalenceCertificate {
        /// JSON property `certificateId`.
        pub certificate_id: CertificateId,
        /// JSON property `coverageStatusIds`.
        pub coverage_status_ids: Vec<GuaranteeStatusId>,
        /// JSON property `evidenceDigest`.
        pub evidence_digest: Option<crate::Digest>,
        /// JSON property `leftSnapshotId`.
        pub left_snapshot_id: SnapshotId,
        /// JSON property `outcome`.
        pub outcome: EquivalenceOutcome,
        /// JSON property `profileId`.
        pub profile_id: String,
        /// JSON property `rightSnapshotId`.
        pub right_snapshot_id: SnapshotId,
        /// Unknown extension members retained without granting them core authority.
        pub extensions: crate::ExtensionMap,
    }

    impl EquivalenceCertificate {
        /// Construct the entity with every machine-required property present.
        #[allow(clippy::too_many_arguments)]
        pub fn new(
            certificate_id: CertificateId,
            left_snapshot_id: SnapshotId,
            right_snapshot_id: SnapshotId,
            profile_id: String,
            outcome: EquivalenceOutcome,
            coverage_status_ids: Vec<GuaranteeStatusId>,
        ) -> Self {
            Self {
                certificate_id,
                coverage_status_ids,
                evidence_digest: None,
                left_snapshot_id,
                outcome,
                profile_id,
                right_snapshot_id,
                extensions: crate::ExtensionMap::new(),
            }
        }
    }

    #[derive(Clone, Debug, PartialEq)]
    pub struct LineageCertificate {
        /// JSON property `evidenceDigest`.
        pub evidence_digest: Option<crate::Digest>,
        /// JSON property `lineageCertificateId`.
        pub lineage_certificate_id: LineageCertificateId,
        /// JSON property `predecessorUnitIds`.
        pub predecessor_unit_ids: Vec<UnitId>,
        /// JSON property `status`.
        pub status: AssertionStatus,
        /// JSON property `successorUnitIds`.
        pub successor_unit_ids: Vec<UnitId>,
        /// Unknown extension members retained without granting them core authority.
        pub extensions: crate::ExtensionMap,
    }

    impl LineageCertificate {
        /// Construct the entity with every machine-required property present.
        #[allow(clippy::too_many_arguments)]
        pub fn new(
            lineage_certificate_id: LineageCertificateId,
            predecessor_unit_ids: Vec<UnitId>,
            successor_unit_ids: Vec<UnitId>,
            status: AssertionStatus,
        ) -> Self {
            Self {
                evidence_digest: None,
                lineage_certificate_id,
                predecessor_unit_ids,
                status,
                successor_unit_ids,
                extensions: crate::ExtensionMap::new(),
            }
        }
    }

    #[derive(Clone, Debug, PartialEq)]
    pub struct Diagnostic {
        /// JSON property `code`.
        pub code: String,
        /// JSON property `diagnosticId`.
        pub diagnostic_id: DiagnosticId,
        /// JSON property `message`.
        pub message: String,
        /// JSON property `relatedIds`.
        pub related_ids: Option<Vec<OpaqueId>>,
        /// JSON property `severity`.
        pub severity: DiagnosticSeverity,
        /// Unknown extension members retained without granting them core authority.
        pub extensions: crate::ExtensionMap,
    }

    impl Diagnostic {
        /// Construct the entity with every machine-required property present.
        #[allow(clippy::too_many_arguments)]
        pub fn new(
            diagnostic_id: DiagnosticId,
            code: String,
            severity: DiagnosticSeverity,
            message: String,
        ) -> Self {
            Self {
                code,
                diagnostic_id,
                message,
                related_ids: None,
                severity,
                extensions: crate::ExtensionMap::new(),
            }
        }
    }

    #[derive(Clone, Debug, PartialEq)]
    pub struct Snapshot {
        /// JSON property `acceptedProjections`.
        pub accepted_projections: Option<Vec<AcceptedProjection>>,
        /// JSON property `accountingItems`.
        pub accounting_items: Vec<AccountingItem>,
        /// JSON property `artifacts`.
        pub artifacts: Vec<Artifact>,
        /// JSON property `assertions`.
        pub assertions: Vec<RecordAssertion>,
        /// JSON property `carriers`.
        pub carriers: Vec<Carrier>,
        /// JSON property `censusReceipts`.
        pub census_receipts: Option<Vec<IndependentCensusReceipt>>,
        /// JSON property `claims`.
        pub claims: Option<crate::ObjectValue>,
        /// JSON property `diagnostics`.
        pub diagnostics: Vec<Diagnostic>,
        /// JSON property `equivalenceCertificates`.
        pub equivalence_certificates: Option<Vec<EquivalenceCertificate>>,
        /// JSON property `fdirVersion`.
        pub fdir_version: String,
        /// JSON property `geometries`.
        pub geometries: Option<Vec<Geometry>>,
        /// JSON property `guaranteeStatuses`.
        pub guarantee_statuses: Vec<GuaranteeStatus>,
        /// JSON property `interpretationContexts`.
        pub interpretation_contexts: Option<Vec<InterpretationContext>>,
        /// JSON property `inventoryDomains`.
        pub inventory_domains: Vec<InventoryDomain>,
        /// JSON property `lineageCertificates`.
        pub lineage_certificates: Option<Vec<LineageCertificate>>,
        /// JSON property `observations`.
        pub observations: Option<Vec<Observation>>,
        /// JSON property `occurrences`.
        pub occurrences: Vec<Occurrence>,
        /// JSON property `relations`.
        pub relations: Vec<InformationRelation>,
        /// JSON property `selectors`.
        pub selectors: Vec<Selector>,
        /// JSON property `snapshotId`.
        pub snapshot_id: SnapshotId,
        /// JSON property `surfaces`.
        pub surfaces: Option<Vec<Surface>>,
        /// JSON property `units`.
        pub units: Vec<InformationUnit>,
        /// Unknown extension members retained without granting them core authority.
        pub extensions: crate::ExtensionMap,
    }

    impl Snapshot {
        /// Construct the entity with every machine-required property present.
        #[allow(clippy::too_many_arguments)]
        pub fn new(
            snapshot_id: SnapshotId,
            artifacts: Vec<Artifact>,
            carriers: Vec<Carrier>,
            selectors: Vec<Selector>,
            occurrences: Vec<Occurrence>,
            units: Vec<InformationUnit>,
            assertions: Vec<RecordAssertion>,
            relations: Vec<InformationRelation>,
            inventory_domains: Vec<InventoryDomain>,
            accounting_items: Vec<AccountingItem>,
            guarantee_statuses: Vec<GuaranteeStatus>,
            diagnostics: Vec<Diagnostic>,
        ) -> Self {
            Self {
                accepted_projections: None,
                accounting_items,
                artifacts,
                assertions,
                carriers,
                census_receipts: None,
                claims: None,
                diagnostics,
                equivalence_certificates: None,
                fdir_version: MODEL_VERSION.to_owned(),
                geometries: None,
                guarantee_statuses,
                interpretation_contexts: None,
                inventory_domains,
                lineage_certificates: None,
                observations: None,
                occurrences,
                relations,
                selectors,
                snapshot_id,
                surfaces: None,
                units,
                extensions: crate::ExtensionMap::new(),
            }
        }
    }

    const ARTIFACT_PROPERTIES: &[crate::PropertySpec] = &[
        crate::PropertySpec {
            json_name: "artifactId",
            rust_name: "artifact_id",
            kind: crate::PropertyKind::Id,
            required: true,
            target: None,
            enumeration: None,
            constant: None,
            minimum: None,
            maximum: None,
            min_items: None,
            max_items: None,
        },
        crate::PropertySpec {
            json_name: "byteLength",
            rust_name: "byte_length",
            kind: crate::PropertyKind::Integer,
            required: false,
            target: None,
            enumeration: None,
            constant: None,
            minimum: Some(0.0),
            maximum: None,
            min_items: None,
            max_items: None,
        },
        crate::PropertySpec {
            json_name: "digest",
            rust_name: "digest",
            kind: crate::PropertyKind::Digest,
            required: true,
            target: None,
            enumeration: None,
            constant: None,
            minimum: None,
            maximum: None,
            min_items: None,
            max_items: None,
        },
        crate::PropertySpec {
            json_name: "mediaType",
            rust_name: "media_type",
            kind: crate::PropertyKind::String,
            required: true,
            target: None,
            enumeration: None,
            constant: None,
            minimum: None,
            maximum: None,
            min_items: None,
            max_items: None,
        },
        crate::PropertySpec {
            json_name: "role",
            rust_name: "role",
            kind: crate::PropertyKind::String,
            required: false,
            target: None,
            enumeration: None,
            constant: None,
            minimum: None,
            maximum: None,
            min_items: None,
            max_items: None,
        },
    ];

    const CARRIER_PROPERTIES: &[crate::PropertySpec] = &[
        crate::PropertySpec {
            json_name: "artifactId",
            rust_name: "artifact_id",
            kind: crate::PropertyKind::Reference,
            required: true,
            target: Some("Artifact"),
            enumeration: None,
            constant: None,
            minimum: None,
            maximum: None,
            min_items: None,
            max_items: None,
        },
        crate::PropertySpec {
            json_name: "carrierId",
            rust_name: "carrier_id",
            kind: crate::PropertyKind::Id,
            required: true,
            target: None,
            enumeration: None,
            constant: None,
            minimum: None,
            maximum: None,
            min_items: None,
            max_items: None,
        },
        crate::PropertySpec {
            json_name: "carrierType",
            rust_name: "carrier_type",
            kind: crate::PropertyKind::String,
            required: true,
            target: None,
            enumeration: None,
            constant: None,
            minimum: None,
            maximum: None,
            min_items: None,
            max_items: None,
        },
        crate::PropertySpec {
            json_name: "path",
            rust_name: "path",
            kind: crate::PropertyKind::String,
            required: false,
            target: None,
            enumeration: None,
            constant: None,
            minimum: None,
            maximum: None,
            min_items: None,
            max_items: None,
        },
    ];

    const SURFACE_PROPERTIES: &[crate::PropertySpec] = &[
        crate::PropertySpec {
            json_name: "carrierId",
            rust_name: "carrier_id",
            kind: crate::PropertyKind::Reference,
            required: true,
            target: Some("Carrier"),
            enumeration: None,
            constant: None,
            minimum: None,
            maximum: None,
            min_items: None,
            max_items: None,
        },
        crate::PropertySpec {
            json_name: "label",
            rust_name: "label",
            kind: crate::PropertyKind::String,
            required: false,
            target: None,
            enumeration: None,
            constant: None,
            minimum: None,
            maximum: None,
            min_items: None,
            max_items: None,
        },
        crate::PropertySpec {
            json_name: "surfaceId",
            rust_name: "surface_id",
            kind: crate::PropertyKind::Id,
            required: true,
            target: None,
            enumeration: None,
            constant: None,
            minimum: None,
            maximum: None,
            min_items: None,
            max_items: None,
        },
        crate::PropertySpec {
            json_name: "surfaceType",
            rust_name: "surface_type",
            kind: crate::PropertyKind::String,
            required: true,
            target: None,
            enumeration: None,
            constant: None,
            minimum: None,
            maximum: None,
            min_items: None,
            max_items: None,
        },
    ];

    const GEOMETRY_PROPERTIES: &[crate::PropertySpec] = &[
        crate::PropertySpec {
            json_name: "bounds",
            rust_name: "bounds",
            kind: crate::PropertyKind::NumberArray,
            required: true,
            target: None,
            enumeration: None,
            constant: None,
            minimum: None,
            maximum: None,
            min_items: Some(4),
            max_items: Some(4),
        },
        crate::PropertySpec {
            json_name: "coordinateSpace",
            rust_name: "coordinate_space",
            kind: crate::PropertyKind::String,
            required: true,
            target: None,
            enumeration: None,
            constant: None,
            minimum: None,
            maximum: None,
            min_items: None,
            max_items: None,
        },
        crate::PropertySpec {
            json_name: "geometryId",
            rust_name: "geometry_id",
            kind: crate::PropertyKind::Id,
            required: true,
            target: None,
            enumeration: None,
            constant: None,
            minimum: None,
            maximum: None,
            min_items: None,
            max_items: None,
        },
        crate::PropertySpec {
            json_name: "surfaceId",
            rust_name: "surface_id",
            kind: crate::PropertyKind::Reference,
            required: true,
            target: Some("Surface"),
            enumeration: None,
            constant: None,
            minimum: None,
            maximum: None,
            min_items: None,
            max_items: None,
        },
    ];

    const SELECTOR_PROPERTIES: &[crate::PropertySpec] = &[
        crate::PropertySpec {
            json_name: "selectorId",
            rust_name: "selector_id",
            kind: crate::PropertyKind::Id,
            required: true,
            target: None,
            enumeration: None,
            constant: None,
            minimum: None,
            maximum: None,
            min_items: None,
            max_items: None,
        },
        crate::PropertySpec {
            json_name: "selectorType",
            rust_name: "selector_type",
            kind: crate::PropertyKind::String,
            required: true,
            target: None,
            enumeration: None,
            constant: None,
            minimum: None,
            maximum: None,
            min_items: None,
            max_items: None,
        },
        crate::PropertySpec {
            json_name: "value",
            rust_name: "value",
            kind: crate::PropertyKind::Object,
            required: true,
            target: None,
            enumeration: None,
            constant: None,
            minimum: None,
            maximum: None,
            min_items: None,
            max_items: None,
        },
    ];

    const OCCURRENCE_PROPERTIES: &[crate::PropertySpec] = &[
        crate::PropertySpec {
            json_name: "carrierId",
            rust_name: "carrier_id",
            kind: crate::PropertyKind::Reference,
            required: true,
            target: Some("Carrier"),
            enumeration: None,
            constant: None,
            minimum: None,
            maximum: None,
            min_items: None,
            max_items: None,
        },
        crate::PropertySpec {
            json_name: "geometryIds",
            rust_name: "geometry_ids",
            kind: crate::PropertyKind::ReferenceArray,
            required: false,
            target: Some("Geometry"),
            enumeration: None,
            constant: None,
            minimum: None,
            maximum: None,
            min_items: None,
            max_items: None,
        },
        crate::PropertySpec {
            json_name: "occurrenceId",
            rust_name: "occurrence_id",
            kind: crate::PropertyKind::Id,
            required: true,
            target: None,
            enumeration: None,
            constant: None,
            minimum: None,
            maximum: None,
            min_items: None,
            max_items: None,
        },
        crate::PropertySpec {
            json_name: "selectorIds",
            rust_name: "selector_ids",
            kind: crate::PropertyKind::ReferenceArray,
            required: true,
            target: Some("Selector"),
            enumeration: None,
            constant: None,
            minimum: None,
            maximum: None,
            min_items: None,
            max_items: None,
        },
    ];

    const OBSERVATION_PROPERTIES: &[crate::PropertySpec] = &[
        crate::PropertySpec {
            json_name: "confidence",
            rust_name: "confidence",
            kind: crate::PropertyKind::Number,
            required: false,
            target: None,
            enumeration: None,
            constant: None,
            minimum: Some(0.0),
            maximum: Some(1.0),
            min_items: None,
            max_items: None,
        },
        crate::PropertySpec {
            json_name: "method",
            rust_name: "method",
            kind: crate::PropertyKind::String,
            required: true,
            target: None,
            enumeration: None,
            constant: None,
            minimum: None,
            maximum: None,
            min_items: None,
            max_items: None,
        },
        crate::PropertySpec {
            json_name: "observationId",
            rust_name: "observation_id",
            kind: crate::PropertyKind::Id,
            required: true,
            target: None,
            enumeration: None,
            constant: None,
            minimum: None,
            maximum: None,
            min_items: None,
            max_items: None,
        },
        crate::PropertySpec {
            json_name: "occurrenceId",
            rust_name: "occurrence_id",
            kind: crate::PropertyKind::Reference,
            required: true,
            target: Some("Occurrence"),
            enumeration: None,
            constant: None,
            minimum: None,
            maximum: None,
            min_items: None,
            max_items: None,
        },
        crate::PropertySpec {
            json_name: "value",
            rust_name: "value",
            kind: crate::PropertyKind::Any,
            required: true,
            target: None,
            enumeration: None,
            constant: None,
            minimum: None,
            maximum: None,
            min_items: None,
            max_items: None,
        },
    ];

    const INVENTORY_DOMAIN_PROPERTIES: &[crate::PropertySpec] = &[
        crate::PropertySpec {
            json_name: "carrierId",
            rust_name: "carrier_id",
            kind: crate::PropertyKind::Reference,
            required: true,
            target: Some("Carrier"),
            enumeration: None,
            constant: None,
            minimum: None,
            maximum: None,
            min_items: None,
            max_items: None,
        },
        crate::PropertySpec {
            json_name: "domainType",
            rust_name: "domain_type",
            kind: crate::PropertyKind::String,
            required: true,
            target: None,
            enumeration: None,
            constant: None,
            minimum: None,
            maximum: None,
            min_items: None,
            max_items: None,
        },
        crate::PropertySpec {
            json_name: "expectedCount",
            rust_name: "expected_count",
            kind: crate::PropertyKind::Integer,
            required: false,
            target: None,
            enumeration: None,
            constant: None,
            minimum: Some(0.0),
            maximum: None,
            min_items: None,
            max_items: None,
        },
        crate::PropertySpec {
            json_name: "inventoryDomainId",
            rust_name: "inventory_domain_id",
            kind: crate::PropertyKind::Id,
            required: true,
            target: None,
            enumeration: None,
            constant: None,
            minimum: None,
            maximum: None,
            min_items: None,
            max_items: None,
        },
    ];

    const ACCOUNTING_ITEM_PROPERTIES: &[crate::PropertySpec] = &[
        crate::PropertySpec {
            json_name: "accountingItemId",
            rust_name: "accounting_item_id",
            kind: crate::PropertyKind::Id,
            required: true,
            target: None,
            enumeration: None,
            constant: None,
            minimum: None,
            maximum: None,
            min_items: None,
            max_items: None,
        },
        crate::PropertySpec {
            json_name: "diagnosticIds",
            rust_name: "diagnostic_ids",
            kind: crate::PropertyKind::ReferenceArray,
            required: false,
            target: Some("Diagnostic"),
            enumeration: None,
            constant: None,
            minimum: None,
            maximum: None,
            min_items: None,
            max_items: None,
        },
        crate::PropertySpec {
            json_name: "disposition",
            rust_name: "disposition",
            kind: crate::PropertyKind::Enumeration,
            required: true,
            target: None,
            enumeration: Some("AccountingDisposition"),
            constant: None,
            minimum: None,
            maximum: None,
            min_items: None,
            max_items: None,
        },
        crate::PropertySpec {
            json_name: "inventoryDomainId",
            rust_name: "inventory_domain_id",
            kind: crate::PropertyKind::Reference,
            required: true,
            target: Some("InventoryDomain"),
            enumeration: None,
            constant: None,
            minimum: None,
            maximum: None,
            min_items: None,
            max_items: None,
        },
        crate::PropertySpec {
            json_name: "sourceKey",
            rust_name: "source_key",
            kind: crate::PropertyKind::String,
            required: true,
            target: None,
            enumeration: None,
            constant: None,
            minimum: None,
            maximum: None,
            min_items: None,
            max_items: None,
        },
        crate::PropertySpec {
            json_name: "unitIds",
            rust_name: "unit_ids",
            kind: crate::PropertyKind::ReferenceArray,
            required: false,
            target: Some("InformationUnit"),
            enumeration: None,
            constant: None,
            minimum: None,
            maximum: None,
            min_items: None,
            max_items: None,
        },
    ];

    const INDEPENDENT_CENSUS_RECEIPT_PROPERTIES: &[crate::PropertySpec] = &[
        crate::PropertySpec {
            json_name: "digest",
            rust_name: "digest",
            kind: crate::PropertyKind::Digest,
            required: true,
            target: None,
            enumeration: None,
            constant: None,
            minimum: None,
            maximum: None,
            min_items: None,
            max_items: None,
        },
        crate::PropertySpec {
            json_name: "inventoryDomainId",
            rust_name: "inventory_domain_id",
            kind: crate::PropertyKind::Reference,
            required: true,
            target: Some("InventoryDomain"),
            enumeration: None,
            constant: None,
            minimum: None,
            maximum: None,
            min_items: None,
            max_items: None,
        },
        crate::PropertySpec {
            json_name: "observedCount",
            rust_name: "observed_count",
            kind: crate::PropertyKind::Integer,
            required: true,
            target: None,
            enumeration: None,
            constant: None,
            minimum: Some(0.0),
            maximum: None,
            min_items: None,
            max_items: None,
        },
        crate::PropertySpec {
            json_name: "receiptId",
            rust_name: "receipt_id",
            kind: crate::PropertyKind::Id,
            required: true,
            target: None,
            enumeration: None,
            constant: None,
            minimum: None,
            maximum: None,
            min_items: None,
            max_items: None,
        },
    ];

    const INFORMATION_UNIT_PROPERTIES: &[crate::PropertySpec] = &[
        crate::PropertySpec {
            json_name: "unitId",
            rust_name: "unit_id",
            kind: crate::PropertyKind::Id,
            required: true,
            target: None,
            enumeration: None,
            constant: None,
            minimum: None,
            maximum: None,
            min_items: None,
            max_items: None,
        },
    ];

    const RECORD_ASSERTION_PROPERTIES: &[crate::PropertySpec] = &[
        crate::PropertySpec {
            json_name: "assertionId",
            rust_name: "assertion_id",
            kind: crate::PropertyKind::Id,
            required: true,
            target: None,
            enumeration: None,
            constant: None,
            minimum: None,
            maximum: None,
            min_items: None,
            max_items: None,
        },
        crate::PropertySpec {
            json_name: "confidence",
            rust_name: "confidence",
            kind: crate::PropertyKind::Number,
            required: false,
            target: None,
            enumeration: None,
            constant: None,
            minimum: Some(0.0),
            maximum: Some(1.0),
            min_items: None,
            max_items: None,
        },
        crate::PropertySpec {
            json_name: "contextId",
            rust_name: "context_id",
            kind: crate::PropertyKind::Reference,
            required: false,
            target: Some("InterpretationContext"),
            enumeration: None,
            constant: None,
            minimum: None,
            maximum: None,
            min_items: None,
            max_items: None,
        },
        crate::PropertySpec {
            json_name: "occurrenceIds",
            rust_name: "occurrence_ids",
            kind: crate::PropertyKind::ReferenceArray,
            required: true,
            target: Some("Occurrence"),
            enumeration: None,
            constant: None,
            minimum: None,
            maximum: None,
            min_items: None,
            max_items: None,
        },
        crate::PropertySpec {
            json_name: "predicate",
            rust_name: "predicate",
            kind: crate::PropertyKind::String,
            required: true,
            target: None,
            enumeration: None,
            constant: None,
            minimum: None,
            maximum: None,
            min_items: None,
            max_items: None,
        },
        crate::PropertySpec {
            json_name: "status",
            rust_name: "status",
            kind: crate::PropertyKind::Enumeration,
            required: true,
            target: None,
            enumeration: Some("AssertionStatus"),
            constant: None,
            minimum: None,
            maximum: None,
            min_items: None,
            max_items: None,
        },
        crate::PropertySpec {
            json_name: "unitId",
            rust_name: "unit_id",
            kind: crate::PropertyKind::Reference,
            required: true,
            target: Some("InformationUnit"),
            enumeration: None,
            constant: None,
            minimum: None,
            maximum: None,
            min_items: None,
            max_items: None,
        },
        crate::PropertySpec {
            json_name: "value",
            rust_name: "value",
            kind: crate::PropertyKind::Any,
            required: true,
            target: None,
            enumeration: None,
            constant: None,
            minimum: None,
            maximum: None,
            min_items: None,
            max_items: None,
        },
    ];

    const INFORMATION_RELATION_PROPERTIES: &[crate::PropertySpec] = &[
        crate::PropertySpec {
            json_name: "occurrenceIds",
            rust_name: "occurrence_ids",
            kind: crate::PropertyKind::ReferenceArray,
            required: false,
            target: Some("Occurrence"),
            enumeration: None,
            constant: None,
            minimum: None,
            maximum: None,
            min_items: None,
            max_items: None,
        },
        crate::PropertySpec {
            json_name: "relationId",
            rust_name: "relation_id",
            kind: crate::PropertyKind::Id,
            required: true,
            target: None,
            enumeration: None,
            constant: None,
            minimum: None,
            maximum: None,
            min_items: None,
            max_items: None,
        },
        crate::PropertySpec {
            json_name: "relationKind",
            rust_name: "relation_kind",
            kind: crate::PropertyKind::Enumeration,
            required: true,
            target: None,
            enumeration: Some("RelationKind"),
            constant: None,
            minimum: None,
            maximum: None,
            min_items: None,
            max_items: None,
        },
        crate::PropertySpec {
            json_name: "sourceUnitId",
            rust_name: "source_unit_id",
            kind: crate::PropertyKind::Reference,
            required: true,
            target: Some("InformationUnit"),
            enumeration: None,
            constant: None,
            minimum: None,
            maximum: None,
            min_items: None,
            max_items: None,
        },
        crate::PropertySpec {
            json_name: "status",
            rust_name: "status",
            kind: crate::PropertyKind::Enumeration,
            required: true,
            target: None,
            enumeration: Some("AssertionStatus"),
            constant: None,
            minimum: None,
            maximum: None,
            min_items: None,
            max_items: None,
        },
        crate::PropertySpec {
            json_name: "targetUnitId",
            rust_name: "target_unit_id",
            kind: crate::PropertyKind::Reference,
            required: true,
            target: Some("InformationUnit"),
            enumeration: None,
            constant: None,
            minimum: None,
            maximum: None,
            min_items: None,
            max_items: None,
        },
    ];

    const ACCEPTED_PROJECTION_PROPERTIES: &[crate::PropertySpec] = &[
        crate::PropertySpec {
            json_name: "assertionIds",
            rust_name: "assertion_ids",
            kind: crate::PropertyKind::ReferenceArray,
            required: true,
            target: Some("RecordAssertion"),
            enumeration: None,
            constant: None,
            minimum: None,
            maximum: None,
            min_items: None,
            max_items: None,
        },
        crate::PropertySpec {
            json_name: "projectionId",
            rust_name: "projection_id",
            kind: crate::PropertyKind::Id,
            required: true,
            target: None,
            enumeration: None,
            constant: None,
            minimum: None,
            maximum: None,
            min_items: None,
            max_items: None,
        },
        crate::PropertySpec {
            json_name: "unitId",
            rust_name: "unit_id",
            kind: crate::PropertyKind::Reference,
            required: true,
            target: Some("InformationUnit"),
            enumeration: None,
            constant: None,
            minimum: None,
            maximum: None,
            min_items: None,
            max_items: None,
        },
        crate::PropertySpec {
            json_name: "value",
            rust_name: "value",
            kind: crate::PropertyKind::Object,
            required: false,
            target: None,
            enumeration: None,
            constant: None,
            minimum: None,
            maximum: None,
            min_items: None,
            max_items: None,
        },
    ];

    const INTERPRETATION_CONTEXT_PROPERTIES: &[crate::PropertySpec] = &[
        crate::PropertySpec {
            json_name: "contextId",
            rust_name: "context_id",
            kind: crate::PropertyKind::Id,
            required: true,
            target: None,
            enumeration: None,
            constant: None,
            minimum: None,
            maximum: None,
            min_items: None,
            max_items: None,
        },
        crate::PropertySpec {
            json_name: "parameters",
            rust_name: "parameters",
            kind: crate::PropertyKind::Object,
            required: true,
            target: None,
            enumeration: None,
            constant: None,
            minimum: None,
            maximum: None,
            min_items: None,
            max_items: None,
        },
    ];

    const GUARANTEE_STATUS_PROPERTIES: &[crate::PropertySpec] = &[
        crate::PropertySpec {
            json_name: "diagnosticIds",
            rust_name: "diagnostic_ids",
            kind: crate::PropertyKind::ReferenceArray,
            required: false,
            target: Some("Diagnostic"),
            enumeration: None,
            constant: None,
            minimum: None,
            maximum: None,
            min_items: None,
            max_items: None,
        },
        crate::PropertySpec {
            json_name: "guaranteeStatusId",
            rust_name: "guarantee_status_id",
            kind: crate::PropertyKind::Id,
            required: true,
            target: None,
            enumeration: None,
            constant: None,
            minimum: None,
            maximum: None,
            min_items: None,
            max_items: None,
        },
        crate::PropertySpec {
            json_name: "profileId",
            rust_name: "profile_id",
            kind: crate::PropertyKind::String,
            required: true,
            target: None,
            enumeration: None,
            constant: None,
            minimum: None,
            maximum: None,
            min_items: None,
            max_items: None,
        },
        crate::PropertySpec {
            json_name: "state",
            rust_name: "state",
            kind: crate::PropertyKind::Enumeration,
            required: true,
            target: None,
            enumeration: Some("CompletenessState"),
            constant: None,
            minimum: None,
            maximum: None,
            min_items: None,
            max_items: None,
        },
    ];

    const EQUIVALENCE_CERTIFICATE_PROPERTIES: &[crate::PropertySpec] = &[
        crate::PropertySpec {
            json_name: "certificateId",
            rust_name: "certificate_id",
            kind: crate::PropertyKind::Id,
            required: true,
            target: None,
            enumeration: None,
            constant: None,
            minimum: None,
            maximum: None,
            min_items: None,
            max_items: None,
        },
        crate::PropertySpec {
            json_name: "coverageStatusIds",
            rust_name: "coverage_status_ids",
            kind: crate::PropertyKind::ReferenceArray,
            required: true,
            target: Some("GuaranteeStatus"),
            enumeration: None,
            constant: None,
            minimum: None,
            maximum: None,
            min_items: None,
            max_items: None,
        },
        crate::PropertySpec {
            json_name: "evidenceDigest",
            rust_name: "evidence_digest",
            kind: crate::PropertyKind::Digest,
            required: false,
            target: None,
            enumeration: None,
            constant: None,
            minimum: None,
            maximum: None,
            min_items: None,
            max_items: None,
        },
        crate::PropertySpec {
            json_name: "leftSnapshotId",
            rust_name: "left_snapshot_id",
            kind: crate::PropertyKind::Id,
            required: true,
            target: None,
            enumeration: None,
            constant: None,
            minimum: None,
            maximum: None,
            min_items: None,
            max_items: None,
        },
        crate::PropertySpec {
            json_name: "outcome",
            rust_name: "outcome",
            kind: crate::PropertyKind::Enumeration,
            required: true,
            target: None,
            enumeration: Some("EquivalenceOutcome"),
            constant: None,
            minimum: None,
            maximum: None,
            min_items: None,
            max_items: None,
        },
        crate::PropertySpec {
            json_name: "profileId",
            rust_name: "profile_id",
            kind: crate::PropertyKind::String,
            required: true,
            target: None,
            enumeration: None,
            constant: None,
            minimum: None,
            maximum: None,
            min_items: None,
            max_items: None,
        },
        crate::PropertySpec {
            json_name: "rightSnapshotId",
            rust_name: "right_snapshot_id",
            kind: crate::PropertyKind::Id,
            required: true,
            target: None,
            enumeration: None,
            constant: None,
            minimum: None,
            maximum: None,
            min_items: None,
            max_items: None,
        },
    ];

    const LINEAGE_CERTIFICATE_PROPERTIES: &[crate::PropertySpec] = &[
        crate::PropertySpec {
            json_name: "evidenceDigest",
            rust_name: "evidence_digest",
            kind: crate::PropertyKind::Digest,
            required: false,
            target: None,
            enumeration: None,
            constant: None,
            minimum: None,
            maximum: None,
            min_items: None,
            max_items: None,
        },
        crate::PropertySpec {
            json_name: "lineageCertificateId",
            rust_name: "lineage_certificate_id",
            kind: crate::PropertyKind::Id,
            required: true,
            target: None,
            enumeration: None,
            constant: None,
            minimum: None,
            maximum: None,
            min_items: None,
            max_items: None,
        },
        crate::PropertySpec {
            json_name: "predecessorUnitIds",
            rust_name: "predecessor_unit_ids",
            kind: crate::PropertyKind::IdArray,
            required: true,
            target: None,
            enumeration: None,
            constant: None,
            minimum: None,
            maximum: None,
            min_items: None,
            max_items: None,
        },
        crate::PropertySpec {
            json_name: "status",
            rust_name: "status",
            kind: crate::PropertyKind::Enumeration,
            required: true,
            target: None,
            enumeration: Some("AssertionStatus"),
            constant: None,
            minimum: None,
            maximum: None,
            min_items: None,
            max_items: None,
        },
        crate::PropertySpec {
            json_name: "successorUnitIds",
            rust_name: "successor_unit_ids",
            kind: crate::PropertyKind::IdArray,
            required: true,
            target: None,
            enumeration: None,
            constant: None,
            minimum: None,
            maximum: None,
            min_items: None,
            max_items: None,
        },
    ];

    const DIAGNOSTIC_PROPERTIES: &[crate::PropertySpec] = &[
        crate::PropertySpec {
            json_name: "code",
            rust_name: "code",
            kind: crate::PropertyKind::String,
            required: true,
            target: None,
            enumeration: None,
            constant: None,
            minimum: None,
            maximum: None,
            min_items: None,
            max_items: None,
        },
        crate::PropertySpec {
            json_name: "diagnosticId",
            rust_name: "diagnostic_id",
            kind: crate::PropertyKind::Id,
            required: true,
            target: None,
            enumeration: None,
            constant: None,
            minimum: None,
            maximum: None,
            min_items: None,
            max_items: None,
        },
        crate::PropertySpec {
            json_name: "message",
            rust_name: "message",
            kind: crate::PropertyKind::String,
            required: true,
            target: None,
            enumeration: None,
            constant: None,
            minimum: None,
            maximum: None,
            min_items: None,
            max_items: None,
        },
        crate::PropertySpec {
            json_name: "relatedIds",
            rust_name: "related_ids",
            kind: crate::PropertyKind::IdArray,
            required: false,
            target: None,
            enumeration: None,
            constant: None,
            minimum: None,
            maximum: None,
            min_items: None,
            max_items: None,
        },
        crate::PropertySpec {
            json_name: "severity",
            rust_name: "severity",
            kind: crate::PropertyKind::Enumeration,
            required: true,
            target: None,
            enumeration: Some("DiagnosticSeverity"),
            constant: None,
            minimum: None,
            maximum: None,
            min_items: None,
            max_items: None,
        },
    ];

    const SNAPSHOT_PROPERTIES: &[crate::PropertySpec] = &[
        crate::PropertySpec {
            json_name: "acceptedProjections",
            rust_name: "accepted_projections",
            kind: crate::PropertyKind::EntityArray,
            required: false,
            target: Some("AcceptedProjection"),
            enumeration: None,
            constant: None,
            minimum: None,
            maximum: None,
            min_items: None,
            max_items: None,
        },
        crate::PropertySpec {
            json_name: "accountingItems",
            rust_name: "accounting_items",
            kind: crate::PropertyKind::EntityArray,
            required: true,
            target: Some("AccountingItem"),
            enumeration: None,
            constant: None,
            minimum: None,
            maximum: None,
            min_items: None,
            max_items: None,
        },
        crate::PropertySpec {
            json_name: "artifacts",
            rust_name: "artifacts",
            kind: crate::PropertyKind::EntityArray,
            required: true,
            target: Some("Artifact"),
            enumeration: None,
            constant: None,
            minimum: None,
            maximum: None,
            min_items: None,
            max_items: None,
        },
        crate::PropertySpec {
            json_name: "assertions",
            rust_name: "assertions",
            kind: crate::PropertyKind::EntityArray,
            required: true,
            target: Some("RecordAssertion"),
            enumeration: None,
            constant: None,
            minimum: None,
            maximum: None,
            min_items: None,
            max_items: None,
        },
        crate::PropertySpec {
            json_name: "carriers",
            rust_name: "carriers",
            kind: crate::PropertyKind::EntityArray,
            required: true,
            target: Some("Carrier"),
            enumeration: None,
            constant: None,
            minimum: None,
            maximum: None,
            min_items: None,
            max_items: None,
        },
        crate::PropertySpec {
            json_name: "censusReceipts",
            rust_name: "census_receipts",
            kind: crate::PropertyKind::EntityArray,
            required: false,
            target: Some("IndependentCensusReceipt"),
            enumeration: None,
            constant: None,
            minimum: None,
            maximum: None,
            min_items: None,
            max_items: None,
        },
        crate::PropertySpec {
            json_name: "claims",
            rust_name: "claims",
            kind: crate::PropertyKind::Object,
            required: false,
            target: None,
            enumeration: None,
            constant: None,
            minimum: None,
            maximum: None,
            min_items: None,
            max_items: None,
        },
        crate::PropertySpec {
            json_name: "diagnostics",
            rust_name: "diagnostics",
            kind: crate::PropertyKind::EntityArray,
            required: true,
            target: Some("Diagnostic"),
            enumeration: None,
            constant: None,
            minimum: None,
            maximum: None,
            min_items: None,
            max_items: None,
        },
        crate::PropertySpec {
            json_name: "equivalenceCertificates",
            rust_name: "equivalence_certificates",
            kind: crate::PropertyKind::EntityArray,
            required: false,
            target: Some("EquivalenceCertificate"),
            enumeration: None,
            constant: None,
            minimum: None,
            maximum: None,
            min_items: None,
            max_items: None,
        },
        crate::PropertySpec {
            json_name: "fdirVersion",
            rust_name: "fdir_version",
            kind: crate::PropertyKind::Constant,
            required: true,
            target: None,
            enumeration: None,
            constant: Some("2.1.0"),
            minimum: None,
            maximum: None,
            min_items: None,
            max_items: None,
        },
        crate::PropertySpec {
            json_name: "geometries",
            rust_name: "geometries",
            kind: crate::PropertyKind::EntityArray,
            required: false,
            target: Some("Geometry"),
            enumeration: None,
            constant: None,
            minimum: None,
            maximum: None,
            min_items: None,
            max_items: None,
        },
        crate::PropertySpec {
            json_name: "guaranteeStatuses",
            rust_name: "guarantee_statuses",
            kind: crate::PropertyKind::EntityArray,
            required: true,
            target: Some("GuaranteeStatus"),
            enumeration: None,
            constant: None,
            minimum: None,
            maximum: None,
            min_items: None,
            max_items: None,
        },
        crate::PropertySpec {
            json_name: "interpretationContexts",
            rust_name: "interpretation_contexts",
            kind: crate::PropertyKind::EntityArray,
            required: false,
            target: Some("InterpretationContext"),
            enumeration: None,
            constant: None,
            minimum: None,
            maximum: None,
            min_items: None,
            max_items: None,
        },
        crate::PropertySpec {
            json_name: "inventoryDomains",
            rust_name: "inventory_domains",
            kind: crate::PropertyKind::EntityArray,
            required: true,
            target: Some("InventoryDomain"),
            enumeration: None,
            constant: None,
            minimum: None,
            maximum: None,
            min_items: None,
            max_items: None,
        },
        crate::PropertySpec {
            json_name: "lineageCertificates",
            rust_name: "lineage_certificates",
            kind: crate::PropertyKind::EntityArray,
            required: false,
            target: Some("LineageCertificate"),
            enumeration: None,
            constant: None,
            minimum: None,
            maximum: None,
            min_items: None,
            max_items: None,
        },
        crate::PropertySpec {
            json_name: "observations",
            rust_name: "observations",
            kind: crate::PropertyKind::EntityArray,
            required: false,
            target: Some("Observation"),
            enumeration: None,
            constant: None,
            minimum: None,
            maximum: None,
            min_items: None,
            max_items: None,
        },
        crate::PropertySpec {
            json_name: "occurrences",
            rust_name: "occurrences",
            kind: crate::PropertyKind::EntityArray,
            required: true,
            target: Some("Occurrence"),
            enumeration: None,
            constant: None,
            minimum: None,
            maximum: None,
            min_items: None,
            max_items: None,
        },
        crate::PropertySpec {
            json_name: "relations",
            rust_name: "relations",
            kind: crate::PropertyKind::EntityArray,
            required: true,
            target: Some("InformationRelation"),
            enumeration: None,
            constant: None,
            minimum: None,
            maximum: None,
            min_items: None,
            max_items: None,
        },
        crate::PropertySpec {
            json_name: "selectors",
            rust_name: "selectors",
            kind: crate::PropertyKind::EntityArray,
            required: true,
            target: Some("Selector"),
            enumeration: None,
            constant: None,
            minimum: None,
            maximum: None,
            min_items: None,
            max_items: None,
        },
        crate::PropertySpec {
            json_name: "snapshotId",
            rust_name: "snapshot_id",
            kind: crate::PropertyKind::Id,
            required: true,
            target: None,
            enumeration: None,
            constant: None,
            minimum: None,
            maximum: None,
            min_items: None,
            max_items: None,
        },
        crate::PropertySpec {
            json_name: "surfaces",
            rust_name: "surfaces",
            kind: crate::PropertyKind::EntityArray,
            required: false,
            target: Some("Surface"),
            enumeration: None,
            constant: None,
            minimum: None,
            maximum: None,
            min_items: None,
            max_items: None,
        },
        crate::PropertySpec {
            json_name: "units",
            rust_name: "units",
            kind: crate::PropertyKind::EntityArray,
            required: true,
            target: Some("InformationUnit"),
            enumeration: None,
            constant: None,
            minimum: None,
            maximum: None,
            min_items: None,
            max_items: None,
        },
    ];

    /// Machine-derived entity descriptors used by independent validation.
    pub const ENTITY_SPECS: &[crate::EntitySpec] = &[
        crate::EntitySpec {
            name: "Artifact",
            domain: crate::EntityDomain::Evidence,
            identity: "artifactId",
            properties: ARTIFACT_PROPERTIES,
        },
        crate::EntitySpec {
            name: "Carrier",
            domain: crate::EntityDomain::Evidence,
            identity: "carrierId",
            properties: CARRIER_PROPERTIES,
        },
        crate::EntitySpec {
            name: "Surface",
            domain: crate::EntityDomain::Evidence,
            identity: "surfaceId",
            properties: SURFACE_PROPERTIES,
        },
        crate::EntitySpec {
            name: "Geometry",
            domain: crate::EntityDomain::Evidence,
            identity: "geometryId",
            properties: GEOMETRY_PROPERTIES,
        },
        crate::EntitySpec {
            name: "Selector",
            domain: crate::EntityDomain::Evidence,
            identity: "selectorId",
            properties: SELECTOR_PROPERTIES,
        },
        crate::EntitySpec {
            name: "Occurrence",
            domain: crate::EntityDomain::Evidence,
            identity: "occurrenceId",
            properties: OCCURRENCE_PROPERTIES,
        },
        crate::EntitySpec {
            name: "Observation",
            domain: crate::EntityDomain::Evidence,
            identity: "observationId",
            properties: OBSERVATION_PROPERTIES,
        },
        crate::EntitySpec {
            name: "InventoryDomain",
            domain: crate::EntityDomain::Evidence,
            identity: "inventoryDomainId",
            properties: INVENTORY_DOMAIN_PROPERTIES,
        },
        crate::EntitySpec {
            name: "AccountingItem",
            domain: crate::EntityDomain::Evidence,
            identity: "accountingItemId",
            properties: ACCOUNTING_ITEM_PROPERTIES,
        },
        crate::EntitySpec {
            name: "IndependentCensusReceipt",
            domain: crate::EntityDomain::Evidence,
            identity: "receiptId",
            properties: INDEPENDENT_CENSUS_RECEIPT_PROPERTIES,
        },
        crate::EntitySpec {
            name: "InformationUnit",
            domain: crate::EntityDomain::RecordedInformation,
            identity: "unitId",
            properties: INFORMATION_UNIT_PROPERTIES,
        },
        crate::EntitySpec {
            name: "RecordAssertion",
            domain: crate::EntityDomain::RecordedInformation,
            identity: "assertionId",
            properties: RECORD_ASSERTION_PROPERTIES,
        },
        crate::EntitySpec {
            name: "InformationRelation",
            domain: crate::EntityDomain::RecordedInformation,
            identity: "relationId",
            properties: INFORMATION_RELATION_PROPERTIES,
        },
        crate::EntitySpec {
            name: "AcceptedProjection",
            domain: crate::EntityDomain::RecordedInformation,
            identity: "projectionId",
            properties: ACCEPTED_PROJECTION_PROPERTIES,
        },
        crate::EntitySpec {
            name: "InterpretationContext",
            domain: crate::EntityDomain::RecordedInformation,
            identity: "contextId",
            properties: INTERPRETATION_CONTEXT_PROPERTIES,
        },
        crate::EntitySpec {
            name: "GuaranteeStatus",
            domain: crate::EntityDomain::RecordedInformation,
            identity: "guaranteeStatusId",
            properties: GUARANTEE_STATUS_PROPERTIES,
        },
        crate::EntitySpec {
            name: "EquivalenceCertificate",
            domain: crate::EntityDomain::RecordedInformation,
            identity: "certificateId",
            properties: EQUIVALENCE_CERTIFICATE_PROPERTIES,
        },
        crate::EntitySpec {
            name: "LineageCertificate",
            domain: crate::EntityDomain::RecordedInformation,
            identity: "lineageCertificateId",
            properties: LINEAGE_CERTIFICATE_PROPERTIES,
        },
        crate::EntitySpec {
            name: "Diagnostic",
            domain: crate::EntityDomain::Shared,
            identity: "diagnosticId",
            properties: DIAGNOSTIC_PROPERTIES,
        },
        crate::EntitySpec {
            name: "Snapshot",
            domain: crate::EntityDomain::Root,
            identity: "snapshotId",
            properties: SNAPSHOT_PROPERTIES,
        },
    ];

    /// Machine-derived enumeration descriptors used by independent validation.
    pub const ENUM_SPECS: &[crate::EnumSpec] = &[
        crate::EnumSpec { name: "AccountingDisposition", values: ACCOUNTING_DISPOSITION_VALUES },
        crate::EnumSpec { name: "AssertionStatus", values: ASSERTION_STATUS_VALUES },
        crate::EnumSpec { name: "CompletenessState", values: COMPLETENESS_STATE_VALUES },
        crate::EnumSpec { name: "DiagnosticSeverity", values: DIAGNOSTIC_SEVERITY_VALUES },
        crate::EnumSpec { name: "EquivalenceOutcome", values: EQUIVALENCE_OUTCOME_VALUES },
        crate::EnumSpec { name: "RelationKind", values: RELATION_KIND_VALUES },
        crate::EnumSpec { name: "UnitKind", values: UNIT_KIND_VALUES },
        crate::EnumSpec { name: "Visibility", values: VISIBILITY_VALUES },
    ];

    const ACCOUNTING_DISPOSITION_VALUES: &[&str] = &[
        "represented",
        "residual",
        "unsupported",
        "unreadable",
        "policy-excluded",
        "duplicate",
    ];

    const ASSERTION_STATUS_VALUES: &[&str] = &[
        "accepted",
        "candidate",
        "rejected",
        "superseded",
        "unresolved",
    ];

    const COMPLETENESS_STATE_VALUES: &[&str] = &[
        "complete",
        "partial",
        "unsupported",
        "unresolved",
        "cancelled",
        "failed",
    ];

    const DIAGNOSTIC_SEVERITY_VALUES: &[&str] = &[
        "info",
        "warning",
        "error",
        "fatal",
    ];

    const EQUIVALENCE_OUTCOME_VALUES: &[&str] = &[
        "equivalent",
        "not-equivalent",
        "indeterminate",
    ];

    const RELATION_KIND_VALUES: &[&str] = &[
        "contains",
        "precedes",
        "references",
        "annotates",
        "groups",
        "derived-from",
        "continues",
    ];

    const UNIT_KIND_VALUES: &[&str] = &[
        "document",
        "section",
        "paragraph",
        "span",
        "list",
        "list-item",
        "table",
        "row",
        "cell",
        "figure",
        "formula",
        "field",
        "note",
        "comment",
        "custom",
    ];

    const VISIBILITY_VALUES: &[&str] = &[
        "visible",
        "hidden",
        "conditional",
        "unknown",
    ];

}

pub use generated_contract::*;
