#!/usr/bin/env python3
"""Generate the Rust foundation contract from the frozen FDIR authorities."""
from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
from typing import Any

GENERATED_PATH = Path("crates/fdir-contract/src/generated.rs")
MANIFEST_PATH = Path("quality/rust-generated-contract.json")
MANIFEST_SCHEMA = "fdir/rust-generated-contract/1"


def load_json(path: Path) -> Any:
    return json.loads(path.read_text(encoding="utf-8"))


def rust_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def rust_slice(name: str, values: list[str]) -> list[str]:
    lines = [f"pub const {name}: &[&str] = &["]
    lines.extend(f"    {rust_string(value)}," for value in values)
    lines.append("];")
    return lines


def generated_contract(root: Path) -> str:
    model_path = root / "machine/logical-model.yaml"
    vector_path = root / "fixtures/canonical/vector.json"
    model = load_json(model_path)
    vector_bytes = vector_path.read_bytes()

    entities = model.get("entities")
    enums = model.get("enums")
    if not isinstance(entities, list) or not entities:
        raise ValueError("logical model has no entity registry")
    if not isinstance(enums, dict) or not enums:
        raise ValueError("logical model has no enumeration registry")

    entity_names: list[str] = []
    for index, entity in enumerate(entities):
        if not isinstance(entity, dict) or not isinstance(entity.get("name"), str):
            raise ValueError(f"logical model entity {index} has no name")
        entity_names.append(entity["name"])
    enum_names = sorted(enums)

    model_id = model.get("modelId")
    model_version = model.get("version")
    root_entity = model.get("rootEntity")
    if not all(isinstance(value, str) and value for value in (model_id, model_version, root_entity)):
        raise ValueError("logical model metadata is incomplete")

    lines = [
        "// @generated by tools/generate_rust_contract.py; do not edit.",
        "// The language-neutral machine model and canonical vector remain authoritative.",
        "",
        "/// Identifier of the frozen language-neutral logical model.",
        f"pub const MODEL_ID: &str = {rust_string(model_id)};",
        "/// Version of the frozen language-neutral logical model.",
        f"pub const MODEL_VERSION: &str = {rust_string(model_version)};",
        "/// Root entity declared by the logical model.",
        f"pub const ROOT_ENTITY: &str = {rust_string(root_entity)};",
        "/// SHA-256 of the canonical-vector source bytes.",
        f'pub const CANONICAL_VECTOR_SHA256: &str = "{hashlib.sha256(vector_bytes).hexdigest()}";',
        "/// Byte length of the canonical-vector source.",
        f"pub const CANONICAL_VECTOR_LENGTH: usize = {len(vector_bytes)};",
        "/// Canonical vector compiled directly from the repository authority.",
        "pub const CANONICAL_VECTOR_JSON: &str = include_str!(concat!(",
        '    env!("CARGO_MANIFEST_DIR"),',
        '    "/../../fixtures/canonical/vector.json"',
        "));",
        "",
        "/// Entity names in authority order.",
        *rust_slice("ENTITY_NAMES", entity_names),
        "",
        "/// Enumeration names in deterministic lexical order.",
        *rust_slice("ENUM_NAMES", enum_names),
        "",
    ]
    return "\n".join(lines)


def outputs(root: Path) -> dict[Path, str]:
    generated = generated_contract(root)
    manifest = {
        "canonicalVector": "fixtures/canonical/vector.json",
        "generator": "tools/generate_rust_contract.py",
        "logicalModel": "machine/logical-model.yaml",
        "output": GENERATED_PATH.as_posix(),
        "outputSha256": hashlib.sha256(generated.encode("utf-8")).hexdigest(),
        "schema": MANIFEST_SCHEMA,
    }
    return {
        GENERATED_PATH: generated,
        MANIFEST_PATH: json.dumps(manifest, ensure_ascii=False, indent=2, sort_keys=True) + "\n",
    }


def run(root: Path, check: bool) -> int:
    failures: list[str] = []
    for relative, content in outputs(root).items():
        path = root / relative
        if check:
            if not path.is_file() or path.read_text(encoding="utf-8") != content:
                failures.append(relative.as_posix())
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
    if failures:
        print("generated Rust contract mismatch:")
        for failure in failures:
            print(f"  - {failure}")
        return 1
    print("generated Rust contract: ok" if check else "generated Rust contract: written")
    return 0


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("root", nargs="?", default=".")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    return run(Path(args.root).resolve(), args.check)


if __name__ == "__main__":
    raise SystemExit(main())
