"""Focused, independent-oracle tests for ``independent_index`` (#103).

The expected facts below are deliberately literal reviewed values.  They are
not generated by the index builder, ``query_ir``, or a second walk over the
same metadata.  The negative cases mutate the sidecar, source, or SQLite
database and require opening to fail closed.
"""

from __future__ import annotations

import json
import os
from pathlib import Path
import shutil
import sqlite3
import sys
from typing import Any, Callable


ROOT = Path(__file__).resolve().parents[1]
if str(ROOT / "tools") not in sys.path:
    sys.path.insert(0, str(ROOT / "tools"))

from independent_index import (  # noqa: E402
    IndependentIndexError,
    IndexFieldNotFound,
    build_index,
    manifest_path_for,
    open_index,
)


CALLOUT = ROOT / "examples" / "callout.json"


def _copy(path: Path, destination: Path) -> None:
    shutil.copyfile(path, destination)


def _write_json(path: Path, value: Any) -> None:
    path.write_text(
        json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":")) + "\n",
        encoding="utf-8",
        newline="\n",
    )


def _expect_rejection(label: str, callback: Callable[[], Any]) -> None:
    try:
        callback()
    except (IndependentIndexError, IndexFieldNotFound, OSError, sqlite3.Error, ValueError):
        return
    raise AssertionError(f"negative case was accepted: {label}")


def _independent_expected_facts(index: Any) -> None:
    """Check manually reviewed facts from the callout fixture.

    These values are intentionally not computed from the source document or
    from the index's own rows.  A builder that silently drops nested payload,
    geometry, order, or extension fields cannot satisfy this oracle.
    """

    expected = [
        ("nodes", "node-callout", "/kind", "textBox"),
        ("nodes", "node-callout", "/geometryId", "geometry-callout"),
        ("nodes", "node-callout", "/layoutIds/0", "layout-callout"),
        ("geometries", "geometry-callout", "/primitives/0/width/value", "180"),
        ("geometries", "geometry-callout", "/primitives/0/height/unit", "pt"),
        ("extensions", "extension-docx-callout", "/payload/presetGeometry", "wedgeRoundRectCallout"),
        ("orders", "order-paint", "/items/2/ordinal", 2),
        ("relations", "relation-connector-target", "/toId", "node-paragraph"),
    ]
    for collection, identifier, pointer, value in expected:
        actual = index.get_field(collection, identifier, pointer)
        if actual != value:
            raise AssertionError(
                f"independent oracle mismatch at {collection}/{identifier}{pointer}: "
                f"expected {value!r}, got {actual!r}"
            )

    if index.find_field_equals("/zIndex", 20, collection="layouts") != [
        {"collection": "layouts", "id": "layout-callout"}
    ]:
        raise AssertionError("typed integer field equality was not preserved")
    if index.find_field_equals("/zIndex", "20", collection="layouts"):
        raise AssertionError("integer field was incorrectly compared as text")

    nested = index.reverse_references("surface-page-1")
    if not any(
        item["sourceCollection"] == "layouts"
        and item["sourcePointer"] == "/anchor/surfaceId"
        and item["targetId"] == "surface-page-1"
        for item in nested
    ):
        raise AssertionError("nested anchor reference was not indexed")


def _build_and_check(workspace: Path) -> tuple[Path, Path]:
    source = workspace / "callout.json"
    index_path = workspace / "callout.sqlite"
    _copy(CALLOUT, source)
    manifest = build_index(source, index_path)
    if manifest["schema"] != "fdir/independent-sqlite-index":
        raise AssertionError("unexpected independent index schema")
    if manifest["indexVersion"] != "1.1.0":
        raise AssertionError("unexpected independent index version")
    if manifest["canonicalization"] != "FDIR-IIDX-C14N-1":
        raise AssertionError("canonicalization binding is missing")
    if set(manifest["bindings"]) != {
        "irSchemaSha256", "modelContractSha256", "referenceRegistrySha256",
        "extensionRegistrySha256", "queryContractSha256", "capabilityProfileSha256",
    }:
        raise AssertionError("contract bindings are incomplete")
    if manifest["counts"]["entities"] != 17 or manifest["counts"]["entityFields"] != 173:
        raise AssertionError(f"unexpected persisted row counts: {manifest['counts']}")
    if manifest["counts"]["documentFields"] < 30 or manifest["counts"]["fields"] != manifest["counts"]["entityFields"] + manifest["counts"]["documentFields"]:
        raise AssertionError("document-level facts were not persisted")
    if manifest["contractVersions"]["queryContract"] != "1.3.0":
        raise AssertionError("query contract version binding is missing")
    if manifest["querySurface"]["registeredFieldPathCount"] < 1000:
        raise AssertionError("generated field registry binding is unexpectedly small")
    if manifest["counts"]["references"] < 30:
        raise AssertionError("nested reference coverage is unexpectedly small")

    with open_index(source, index_path) as index:
        _independent_expected_facts(index)
        entities = index.list_entities("nodes", status="preserved")
        if len(entities) != 4:
            raise AssertionError(f"unexpected preserved node count: {len(entities)}")
        try:
            index.get_field("nodes", "node-callout", "/doesNotExist")
        except (IndexFieldNotFound, IndependentIndexError):
            pass
        else:
            raise AssertionError("missing field was not distinguished from a stored value")
        if index.get_field("__document__", "doc-callout", "/conversion/status") != "complete":
            raise AssertionError("document conversion status was not indexed")
        if index.query_fields("/zIndex", 20, collection="layouts") != [
            {"queryContractVersion": "1.3.0", "profileId": "format:docx:ECMA-376:1", "collection": "layouts", "id": "layout-callout", "pointer": "/zIndex", "presence": "value", "value": 20, "status": "preserved"}
        ]:
            raise AssertionError("persistent typed field query did not preserve integer semantics")
        if not any(
            row["sourceId"] == "layout-callout"
            and row["sourcePointer"] == "/anchor/surfaceId"
            and row["targetId"] == "surface-page-1"
            for row in index.find_references("surface-page-1", source_collection="layouts")
        ):
            raise AssertionError("persistent nested reference query mismatch")
        first_page = index.list_entities_page("nodes", limit=2)
        if len(first_page["items"]) != 2 or not first_page["nextCursor"]:
            raise AssertionError("persistent deterministic pagination did not produce a cursor")
        second_page = index.list_entities_page("nodes", limit=2, cursor=first_page["nextCursor"])
        if {item["nodeId"] for item in first_page["items"]}.intersection(item["nodeId"] for item in second_page["items"]):
            raise AssertionError("persistent pagination cursor repeated an entity")
        _expect_rejection(
            "cursor reused with a different query",
            lambda: index.list_entities_page("nodes", status="preserved", limit=2, cursor=first_page["nextCursor"]),
        )

    # Rebuilding the same destination exercises replacement of both the
    # persistent database and its sidecar manifest.
    build_index(source, index_path)
    with open_index(source, index_path) as index:
        _independent_expected_facts(index)
    return source, index_path


def _run_negative_cases(workspace: Path, source: Path, index_path: Path) -> int:
    cases = 0

    stale_source = workspace / "stale-source.json"
    source_value = json.loads(source.read_text(encoding="utf-8"))
    source_value["documentId"] = "doc-callout-stale"
    _write_json(stale_source, source_value)
    _expect_rejection("stale source document", lambda: open_index(stale_source, index_path))
    cases += 1

    wrong_profile = workspace / "wrong-profile.json"
    profile_value = json.loads(source.read_text(encoding="utf-8"))
    profile_value["conversion"]["capabilityProfile"] = "format:xlsx:Office Open XML:1"
    _write_json(wrong_profile, profile_value)
    _expect_rejection("wrong capability profile", lambda: open_index(wrong_profile, index_path))
    cases += 1

    corrupted_manifest = workspace / "corrupted-manifest.sqlite"
    corrupted_manifest_sidecar = manifest_path_for(corrupted_manifest)
    _copy(index_path, corrupted_manifest)
    _copy(manifest_path_for(index_path), corrupted_manifest_sidecar)
    manifest = json.loads(corrupted_manifest_sidecar.read_text(encoding="utf-8"))
    manifest["indexVersion"] = "9.0.0"
    _write_json(corrupted_manifest_sidecar, manifest)
    _expect_rejection(
        "unsupported newer index version",
        lambda: open_index(source, corrupted_manifest),
    )
    cases += 1

    bad_digest = workspace / "bad-digest.sqlite"
    bad_digest_sidecar = manifest_path_for(bad_digest)
    _copy(index_path, bad_digest)
    _copy(manifest_path_for(index_path), bad_digest_sidecar)
    manifest = json.loads(bad_digest_sidecar.read_text(encoding="utf-8"))
    manifest["databaseSha256"] = "0" * 64
    _write_json(bad_digest_sidecar, manifest)
    _expect_rejection("manifest/database digest mismatch", lambda: open_index(source, bad_digest))
    cases += 1

    deleted_row = workspace / "deleted-row.sqlite"
    _copy(index_path, deleted_row)
    _copy(manifest_path_for(index_path), manifest_path_for(deleted_row))
    connection = sqlite3.connect(str(deleted_row))
    connection.execute(
        "DELETE FROM fields WHERE collection = ? AND entity_id = ? AND pointer = ?",
        ("extensions", "extension-docx-callout", "/payload/presetGeometry"),
    )
    connection.commit()
    connection.close()
    _expect_rejection("deleted SQLite field row", lambda: open_index(source, deleted_row))
    cases += 1

    changed_row = workspace / "changed-row.sqlite"
    _copy(index_path, changed_row)
    _copy(manifest_path_for(index_path), manifest_path_for(changed_row))
    connection = sqlite3.connect(str(changed_row))
    connection.execute(
        "UPDATE fields SET value_json = ?, value_sha256 = ? "
        "WHERE collection = ? AND entity_id = ? AND pointer = ?",
        ("\"tampered\"", "0" * 64, "nodes", "node-callout", "/kind"),
    )
    connection.commit()
    connection.close()
    _expect_rejection("changed SQLite field row", lambda: open_index(source, changed_row))
    cases += 1

    truncated = workspace / "truncated.sqlite"
    _copy(index_path, truncated)
    _copy(manifest_path_for(index_path), manifest_path_for(truncated))
    data = truncated.read_bytes()
    truncated.write_bytes(data[: max(1, len(data) // 4)])
    _expect_rejection("partial SQLite write", lambda: open_index(source, truncated))
    cases += 1

    altered_contract = workspace / "altered-query-contract.json"
    altered_contract.write_bytes(
        (ROOT / "machine" / "query-contract.json").read_bytes() + b"\n"
    )
    contract_bound_index = workspace / "contract-bound.sqlite"
    build_index(source, contract_bound_index, query_contract_path=altered_contract)
    _expect_rejection(
        "wrong query-contract binding",
        lambda: open_index(source, contract_bound_index),
    )
    with open_index(source, contract_bound_index, query_contract_path=altered_contract):
        pass
    cases += 1

    return cases


def _run_null_and_missing_case(workspace: Path) -> None:
    source = workspace / "blank-value.json"
    value = json.loads((ROOT / "examples" / "cell-formula.json").read_text(encoding="utf-8"))
    for node in value["nodes"]:
        if node["nodeId"] == "cell-b2":
            node["value"] = {"type": "blank", "value": None, "status": "preserved"}
            break
    else:
        raise AssertionError("cell-formula fixture has no cell-b2")
    _write_json(source, value)
    index_path = workspace / "blank-value.sqlite"
    build_index(source, index_path)
    with open_index(source, index_path) as index:
        if index.get_field("nodes", "cell-b2", "/value/value") is not None:
            raise AssertionError("stored JSON null was not preserved")
        if index.find_field_equals("/value/value", None, collection="nodes") != [
            {"collection": "nodes", "id": "cell-b2"}
        ]:
            raise AssertionError("typed null equality was not preserved")
        _expect_rejection(
            "missing field distinct from null",
            lambda: index.get_field("nodes", "cell-b2", "/value/missing"),
        )


def main() -> int:
    run_root = ROOT / "e2e" / ".run"
    run_root.mkdir(parents=True, exist_ok=True)
    # The managed Windows runner applies a restrictive ACL to Python's
    # TemporaryDirectory.  Use the repository's ignored run scratch area,
    # which is also the CI clean-room convention for generated artifacts.
    workspace = run_root / f"independent-index-focused-{os.getpid()}"
    workspace.mkdir(parents=True, exist_ok=True)
    source, index_path = _build_and_check(workspace)
    negative_cases = _run_negative_cases(workspace, source, index_path)
    _run_null_and_missing_case(workspace)
    if "query_ir" in sys.modules or "query_qualification" in sys.modules:
        raise AssertionError("independent index test imported the direct query implementation")
    result = {
        "schema": "fdir/independent-index-focused-test",
        "status": "passed",
        "positiveOracleFacts": 8,
        "negativeCases": negative_cases,
        "persistentBackend": "sqlite",
        "source": "examples/callout.json",
        "queryIrImported": "query_ir" in sys.modules,
    }
    print(json.dumps(result, ensure_ascii=False, sort_keys=True, separators=(",", ":")))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
