"""Fail closed when the generated model contract drifts from its sources."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys
from typing import Any, List, Optional, Sequence


try:  # Direct script execution from tools/.
    import generate_model_contract as generator
except ImportError:  # Package-style execution.
    from tools import generate_model_contract as generator


PROJECT_ROOT = generator.PROJECT_ROOT
DEFAULT_CONTRACT_PATH = PROJECT_ROOT / "machine" / "model-contract.json"


class ContractValidationError(ValueError):
    """Raised when a contract is missing, malformed, or stale."""


def _read_contract(path: Path) -> tuple[Any, bytes]:
    try:
        encoded = path.read_bytes()
        value = json.loads(encoded.decode("utf-8-sig"))
    except (OSError, UnicodeDecodeError, json.JSONDecodeError) as exc:
        raise ContractValidationError(f"cannot read contract {path}: {exc}") from exc
    if not isinstance(value, dict):
        raise ContractValidationError(f"contract root must be an object: {path}")
    return value, encoded


def _diff(expected: Any, actual: Any, path: str = "$", limit: int = 20) -> List[str]:
    differences: List[str] = []

    def visit(left: Any, right: Any, current: str) -> None:
        if len(differences) >= limit:
            return
        if type(left) is not type(right):
            differences.append(
                f"{current}: expected {type(left).__name__}, got {type(right).__name__}"
            )
            return
        if isinstance(left, dict):
            left_keys = set(left)
            right_keys = set(right)
            for key in sorted(left_keys - right_keys):
                differences.append(f"{current}.{key}: missing from generated contract")
                if len(differences) >= limit:
                    return
            for key in sorted(right_keys - left_keys):
                differences.append(f"{current}.{key}: unexpected generated field")
                if len(differences) >= limit:
                    return
            for key in sorted(left_keys & right_keys):
                visit(left[key], right[key], f"{current}.{key}")
                if len(differences) >= limit:
                    return
            return
        if isinstance(left, list):
            if len(left) != len(right):
                differences.append(
                    f"{current}: expected {len(left)} items, got {len(right)}"
                )
                if len(differences) >= limit:
                    return
            for index, (left_item, right_item) in enumerate(zip(left, right)):
                visit(left_item, right_item, f"{current}[{index}]")
                if len(differences) >= limit:
                    return
            return
        if left != right:
            differences.append(f"{current}: expected {left!r}, got {right!r}")

    visit(expected, actual, path)
    return differences


def _resolve(path: Path) -> Path:
    return path if path.is_absolute() else (PROJECT_ROOT / path).resolve()


def validate_contract(
    contract_path: Path = DEFAULT_CONTRACT_PATH,
    schema_path: Path = generator.DEFAULT_SCHEMA_PATH,
    registry_path: Path = generator.DEFAULT_REGISTRY_PATH,
    runtime_path: Path = generator.DEFAULT_RUNTIME_PATH,
) -> List[str]:
    """Return all current-source and generated-artifact drift findings."""

    contract_path = _resolve(contract_path)
    actual, actual_bytes = _read_contract(contract_path)
    try:
        expected = generator.build_contract(
            schema_path=schema_path,
            registry_path=registry_path,
            runtime_path=runtime_path,
            generator_path=Path(generator.__file__).resolve(),
            root=PROJECT_ROOT,
        )
    except generator.ContractGenerationError as exc:
        raise ContractValidationError(f"source contract cannot be built: {exc}") from exc

    findings: List[str] = []
    expected_bytes = generator._canonical_bytes(expected)
    if actual != expected:
        findings.extend(_diff(expected, actual))
        if len(findings) >= 20:
            findings.append("additional semantic differences omitted")
    if actual_bytes != expected_bytes:
        findings.append(
            "$: generated bytes are not canonical output; run tools/generate_model_contract.py"
        )

    # Check source digests independently as well as through the full expected
    # object comparison.  This keeps the failure actionable if a consumer
    # calls validate_contract() with a partially malformed artifact.
    sources = actual.get("sources")
    if isinstance(sources, list):
        for source in sources:
            if not isinstance(source, dict):
                continue
            path_value = source.get("path")
            declared = source.get("sha256")
            if not isinstance(path_value, str) or not isinstance(declared, str):
                continue
            source_path = _resolve(Path(path_value))
            try:
                observed = generator._sha256_file(source_path)
            except generator.ContractGenerationError as exc:
                findings.append(str(exc))
                continue
            if observed != declared:
                findings.append(
                    f"$.sources[{source.get('role', '?')}].sha256: "
                    f"declared {declared}, observed {observed}"
                )
    else:
        findings.append("$.sources: missing or not an array")
    return findings


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="check the checked-in artifact against freshly derived sources",
    )
    parser.add_argument("--contract", type=Path, default=DEFAULT_CONTRACT_PATH)
    parser.add_argument("--schema", type=Path, default=generator.DEFAULT_SCHEMA_PATH)
    parser.add_argument("--registry", type=Path, default=generator.DEFAULT_REGISTRY_PATH)
    parser.add_argument(
        "--runtime-validator", type=Path, default=generator.DEFAULT_RUNTIME_PATH
    )
    return parser


def main(argv: Optional[Sequence[str]] = None) -> int:
    args = _build_parser().parse_args(argv)
    try:
        findings = validate_contract(
            contract_path=args.contract,
            schema_path=args.schema,
            registry_path=args.registry,
            runtime_path=args.runtime_validator,
        )
    except ContractValidationError as exc:
        print(f"FAIL: {exc}", file=sys.stderr)
        return 1
    if findings:
        print("FAIL: model contract drift detected", file=sys.stderr)
        for finding in findings[:20]:
            print(f"  - {finding}", file=sys.stderr)
        return 1
    print(f"PASS: model contract matches current sources ({_resolve(args.contract)})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
